// Comprehensive English-Urdu Vocabulary Database
// مستند اور جامع انگریزی اردو وکیبلری ڈیٹا بیس

const VOCABULARY_DATA = [
  // ==========================================
  // 1. DAILY ESSENTIALS & ROUTINE (روزمرہ زندگی)
  // ==========================================
  {
    id: 1,
    word: "Punctual",
    phonetic: "/ˈpʌŋk.tʃu.əl/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Daily Life",
    urduMeaning: "وقت کا پابند",
    englishExample: "He is always punctual for his classes.",
    urduExample: "وہ اپنی کلاسوں کے لیے ہمیشہ وقت کا پابند رہتا ہے۔",
    synonyms: ["On time", "Prompt", "Timely"]
  },
  {
    id: 2,
    word: "Routine",
    phonetic: "/ruːˈtiːn/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Daily Life",
    urduMeaning: "روزمرہ کا معمول، روز کا کام",
    englishExample: "Exercise is an important part of my daily routine.",
    urduExample: "ورزش میرے روزمرہ کے معمول کا ایک اہم حصہ ہے۔",
    synonyms: ["Schedule", "Habit", "Pattern"]
  },
  {
    id: 3,
    word: "Commute",
    phonetic: "/kəˈmjuːt/",
    pos: "Verb / Noun (فعل / اسم)",
    level: "Intermediate",
    category: "Daily Life",
    urduMeaning: "روزانہ گھر سے دفتر آنا جانا، سفر کرنا",
    englishExample: "She commutes to work by metro every morning.",
    urduExample: "وہ روزانہ صبح میٹرو کے ذریعے دفتر کا سفر کرتی ہے۔",
    synonyms: ["Travel", "Journey", "Transit"]
  },
  {
    id: 4,
    word: "Leisure",
    phonetic: "/ˈleʒ.ər/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Daily Life",
    urduMeaning: "فراغت، فرصت، آرام کا وقت",
    englishExample: "In my leisure time, I like to read Urdu poetry.",
    urduExample: "فراغت کے وقت میں اردو شاعری پڑھنا پسند کرتا ہوں۔",
    synonyms: ["Free time", "Spare time", "Relaxation"]
  },
  {
    id: 5,
    word: "Habitual",
    phonetic: "/həˈbɪtʃ.u.əl/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Daily Life",
    urduMeaning: "عادی، معمول کے مطابق",
    englishExample: "He took his habitual morning walk in the garden.",
    urduExample: "اس نے باغ میں اپنی معمول کے مطابق صبح کی سیر کی۔",
    synonyms: ["Accustomed", "Customary", "Routine"]
  },
  {
    id: 6,
    word: "Convenient",
    phonetic: "/kənˈviː.ni.ənt/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Daily Life",
    urduMeaning: "آسان، آرام دہ، سہولت بخش",
    englishExample: "Online shopping is very convenient for busy people.",
    urduExample: "آن لائن خریداری مصروف لوگوں کے لیے بہت سہولت بخش ہے۔",
    synonyms: ["Handy", "Suitable", "Accessible"]
  },
  {
    id: 7,
    word: "Household",
    phonetic: "/ˈhaʊs.hoʊld/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Daily Life",
    urduMeaning: "گھریلو، گھرانہ، اہل خانہ",
    englishExample: "Every member shares household chores equally.",
    urduExample: "ہر فرد گھریلو کام کاج میں برابر حصہ لیتا ہے۔",
    synonyms: ["Family", "Domestic", "Home"]
  },
  {
    id: 8,
    word: "Essential",
    phonetic: "/ɪˈsen.ʃəl/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Daily Life",
    urduMeaning: "لازمی، ضروری، بنیادی",
    englishExample: "Clean water is essential for human health.",
    urduExample: "صاف پانی انسانی صحت کے لیے لازمی ہے۔",
    synonyms: ["Crucial", "Vital", "Necessary"]
  },
  {
    id: 9,
    word: "Clutter",
    phonetic: "/ˈklʌt.ər/",
    pos: "Noun / Verb (اسم / فعل)",
    level: "Intermediate",
    category: "Daily Life",
    urduMeaning: "بے ترتیبی، کباڑ، بکھرا ہوا سامان",
    englishExample: "Please clean the clutter off your study table.",
    urduExample: "براہ کرم اپنی پڑھائی کی میز سے بکھرا ہوا سامان صاف کریں۔",
    synonyms: ["Mess", "Jumble", "Disorder"]
  },
  {
    id: 10,
    word: "Errand",
    phonetic: "/ˈer.ənd/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Daily Life",
    urduMeaning: "چھوٹا موٹا کام، سودا سلف لانا",
    englishExample: "I have to run some quick errands in the market.",
    urduExample: "مجھے بازار میں کچھ ضروری چھوٹے موٹے کام نمٹانے ہیں۔",
    synonyms: ["Task", "Chore", "Mission"]
  },

  // ==========================================
  // 2. EMOTIONS & FEELINGS (جذبات و احساسات)
  // ==========================================
  {
    id: 11,
    word: "Grateful",
    phonetic: "/ˈɡreɪt.fəl/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Emotions",
    urduMeaning: "شکر گزار، احسان مند",
    englishExample: "I am grateful for your kind assistance.",
    urduExample: "میں آپ کی مہربانی اور مدد کے لیے شکر گزار ہوں۔",
    synonyms: ["Thankful", "Appreciative", "Obliged"]
  },
  {
    id: 12,
    word: "Anxious",
    phonetic: "/ˈæŋk.ʃəs/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Emotions",
    urduMeaning: "بے چین، فکرمند، پریشان",
    englishExample: "She felt anxious right before the interview.",
    urduExample: "وہ انٹرویو سے ٹھیک پہلے بے چینی اور پریشانی محسوس کر رہی تھی۔",
    synonyms: ["Nervous", "Worried", "Apprehensive"]
  },
  {
    id: 13,
    word: "Ecstatic",
    phonetic: "/ekˈstæt.ɪk/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Emotions",
    urduMeaning: "بے انتہا خوش، مسرور، وجد میں",
    englishExample: "He was ecstatic when he received the scholarship.",
    urduExample: "جب اسے اسکالرشپ ملی تو وہ بے انتہا خوش تھا۔",
    synonyms: ["Overjoyed", "Elated", "Thrilled"]
  },
  {
    id: 14,
    word: "Melancholy",
    phonetic: "/ˈmel.əŋ.kɒl.i/",
    pos: "Noun / Adjective (اسم / صفت)",
    level: "Advanced",
    category: "Emotions",
    urduMeaning: "اداسی، افسردگی، ملال",
    englishExample: "A feeling of melancholy surrounded the empty house.",
    urduExample: "خالی گھر کے اندر اداسی اور ملال کا احساس چھایا ہوا تھا۔",
    synonyms: ["Sadness", "Sorrow", "Gloom"]
  },
  {
    id: 15,
    word: "Empathetic",
    phonetic: "/ˌem.pəˈθet.ɪk/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Emotions",
    urduMeaning: "ہمدرد، دوسروں کے درد کو سمجھنے والا",
    englishExample: "A good doctor is always empathetic toward patients.",
    urduExample: "ایک اچھا ڈاکٹر ہمیشہ مریضوں کے ساتھ ہمدردانہ رویہ رکھتا ہے۔",
    synonyms: ["Compassionate", "Caring", "Understanding"]
  },
  {
    id: 16,
    word: "Furious",
    phonetic: "/ˈfjʊə.ri.əs/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Emotions",
    urduMeaning: "غصے سے پاگل، آگ بگولا، شدید غضبناک",
    englishExample: "He was furious when he discovered the betrayal.",
    urduExample: "جب اسے دھوکے کا علم ہوا تو وہ آگ بگولا ہو گیا۔",
    synonyms: ["Enraged", "Infuriated", "Irate"]
  },
  {
    id: 17,
    word: "Bewildered",
    phonetic: "/bɪˈwɪl.dəd/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Emotions",
    urduMeaning: "حیران و پریشان، ہکا بکا، الجھا ہوا",
    englishExample: "He looked bewildered by the complicated directions.",
    urduExample: "وہ الجھے ہوئے راستے دیکھ کر ہکا بکا رہ گیا۔",
    synonyms: ["Puzzled", "Confused", "Baffled"]
  },
  {
    id: 18,
    word: "Content",
    phonetic: "/kənˈtent/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Emotions",
    urduMeaning: "مطمئن، پرسکون، راضی",
    englishExample: "He is content with a simple and peaceful lifestyle.",
    urduExample: "وہ ایک سادہ اور پرامن طرز زندگی پر مطمئن ہے۔",
    synonyms: ["Satisfied", "Pleased", "Serene"]
  },
  {
    id: 19,
    word: "Homesick",
    phonetic: "/ˈhəʊm.sɪk/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Emotions",
    urduMeaning: "وطن یا گھر کی یاد میں تڑپنے والا",
    englishExample: "Living abroad, he often felt homesick.",
    urduExample: "دیارِ غیر میں رہتے ہوئے، وہ اکثر اپنے گھر کی یاد میں اداس رہتا تھا۔",
    synonyms: ["Nostalgic", "Lonely", "Yearning"]
  },
  {
    id: 20,
    word: "Euphoria",
    phonetic: "/juːˈfɔː.ri.ə/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Emotions",
    urduMeaning: "جوشِ مسرت، انتہائی خوشی اور سرور کی کیفیت",
    englishExample: "The team was in euphoria after winning the World Cup.",
    urduExample: "ورلڈ کپ جیتنے کے بعد ٹیم جوشِ مسرت اور خوشی میں جھوم اٹھی۔",
    synonyms: ["Joy", "Exhilaration", "Bliss"]
  },

  // ==========================================
  // 3. PERSONALITY & CHARACTER (شخصیت و اوصاف)
  // ==========================================
  {
    id: 21,
    word: "Resilient",
    phonetic: "/rɪˈzɪl.jənt/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "ثابت قدم، پرعزم، حالات کا ڈٹ کر مقابلہ کرنے والا",
    englishExample: "The resilient nation recovered quickly after the flood.",
    urduExample: "پرعزم قوم نے سیلاب کے بعد تیزی سے بحالی حاصل کی۔",
    synonyms: ["Tough", "Adaptable", "Enduring"]
  },
  {
    id: 22,
    word: "Diligent",
    phonetic: "/ˈdɪl.ɪ.dʒənt/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "محنتی، انتھک، لگن سے کام کرنے والا",
    englishExample: "Diligent students always achieve their academic dreams.",
    urduExample: "محنتی اور لگن سے پڑھنے والے طلبہ ہمیشہ اپنے تعلیمی خواب پورے کرتے ہیں۔",
    synonyms: ["Hardworking", "Industrious", "Assiduous"]
  },
  {
    id: 23,
    word: "Eloquent",
    phonetic: "/ˈel.ə.kwənt/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "خوش گفتار، فصیح و بلیغ، شیریں زبان",
    englishExample: "The leader gave an eloquent speech that moved the audience.",
    urduExample: "رہنما نے ایسی فصیح و بلیغ تقریر کی جس نے حاضرین کو متاثر کیا۔",
    synonyms: ["Articulate", "Expressive", "Fluent"]
  },
  {
    id: 24,
    word: "Humble",
    phonetic: "/ˈhʌm.bəl/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Personality",
    urduMeaning: "عاجز، منکسر المزاج، بااخلاق",
    englishExample: "Despite all his wealth, he remained extremely humble.",
    urduExample: "اپنی تمام تر دولت کے باوجود وہ انتہائی عاجز اور منکسر المزاج رہا۔",
    synonyms: ["Modest", "Meek", "Unpretentious"]
  },
  {
    id: 25,
    word: "Generous",
    phonetic: "/ˈdʒen.ər.əs/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Personality",
    urduMeaning: "سخی، فیاض، فراخ دل",
    englishExample: "He is famous for his generous donations to charity.",
    urduExample: "وہ رفاہی کاموں میں اپنی فراخ دلانہ عطیات کے لیے مشہور ہے۔",
    synonyms: ["Benevolent", "Charitable", "Magnanimous"]
  },
  {
    id: 26,
    word: "Arrogant",
    phonetic: "/ˈær.ə.ɡənt/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Personality",
    urduMeaning: "مغرور، متکبر، گھمنڈی",
    englishExample: "His arrogant attitude made him unpopular among colleagues.",
    urduExample: "اس کے مغرور رویے نے اسے ساتھیوں میں ناپسندیدہ بنا دیا۔",
    synonyms: ["Haughty", "Conceited", "Pompous"]
  },
  {
    id: 27,
    word: "Courageous",
    phonetic: "/kəˈreɪ.dʒəs/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "بہادر، دلیر، باہمت",
    englishExample: "The courageous soldier risked his life to save others.",
    urduExample: "بہادر سپاہی نے دوسروں کی جان بچانے کے لیے اپنی جان خطرے میں ڈال دی۔",
    synonyms: ["Brave", "Valiant", "Fearless"]
  },
  {
    id: 28,
    word: "Honest",
    phonetic: "/ˈɒn.ɪst/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Personality",
    urduMeaning: "دیانت دار، سچا، امانت دار",
    englishExample: "Honesty is the most respected quality in any profession.",
    urduExample: "دیانت داری کسی بھی پیشے میں سب سے زیادہ قابلِ احترام صفت ہے۔",
    synonyms: ["Truthful", "Sincere", "Trustworthy"]
  },
  {
    id: 29,
    word: "Meticulous",
    phonetic: "/məˈtɪk.jə.ləs/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "نہایت باریک بین، محتاط، ہر پہلو پر توجہ دینے والا",
    englishExample: "She is meticulous about keeping her records organized.",
    urduExample: "وہ اپنے ریکارڈز کو منظم رکھنے میں نہایت باریک بین اور محتاط ہے۔",
    synonyms: ["Thorough", "Painstaking", "Precise"]
  },
  {
    id: 30,
    word: "Stubborn",
    phonetic: "/ˈstʌb.ən/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Personality",
    urduMeaning: "ضدی، اڑیل، اپنی بات پر اڑ جانے والا",
    englishExample: "He was too stubborn to admit that he had made an error.",
    urduExample: "وہ اتنا ضدی تھا کہ اپنی غلطی تسلیم کرنے کو تیار نہ تھا۔",
    synonyms: ["Obstinate", "Headstrong", "Inflexible"]
  },
  {
    id: 31,
    word: "Gregarious",
    phonetic: "/ɡrɪˈɡeə.ri.əs/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "ملنسار، لوگوں میں گھلنے ملنے والا، محفل پسند",
    englishExample: "Being gregarious, he makes new friends effortlessly.",
    urduExample: "ملنسار طبیعت کا مالک ہونے کی وجہ سے وہ آسانی سے نئے دوست بنا لیتا ہے۔",
    synonyms: ["Sociable", "Outgoing", "Friendly"]
  },
  {
    id: 32,
    word: "Candid",
    phonetic: "/ˈkæn.dɪd/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "صاف گو، بے باک، کھرا",
    englishExample: "I appreciate your candid advice on my project.",
    urduExample: "میں اپنے پروجیکٹ پر آپ کے صاف گو اور مخلصانہ مشورے کی قدر کرتا ہوں۔",
    synonyms: ["Frank", "Direct", "Open"]
  },

  // ==========================================
  // 4. EDUCATION, STUDY & SCIENCE (تعلیم، علم و سائنس)
  // ==========================================
  {
    id: 33,
    word: "Comprehend",
    phonetic: "/ˌkɒm.prɪˈhend/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Education",
    urduMeaning: "سمجھنا، ادراک کرنا، فہم حاصل کرنا",
    englishExample: "It took time for the student to comprehend the complex theory.",
    urduExample: "طالب علم کو پیچیدہ نظریہ سمجھنے میں کچھ وقت لگا۔",
    synonyms: ["Understand", "Grasp", "Perceive"]
  },
  {
    id: 34,
    word: "Curiosity",
    phonetic: "/ˌkjʊə.riˈɒs.ə.ti/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Education",
    urduMeaning: "تجسس، جاننے کا شوق، کھوج",
    englishExample: "Scientific inventions begin with simple curiosity.",
    urduExample: "سائنسی ایجادات کا آغاز عام تجسس اور کھوج سے ہوتا ہے۔",
    synonyms: ["Inquisitiveness", "Interest", "Eagerness"]
  },
  {
    id: 35,
    word: "Hypothesis",
    phonetic: "/haɪˈpɒθ.ə.sɪs/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Education",
    urduMeaning: "مفروضہ، قیاس، امکانی رائے",
    englishExample: "The scientists performed experiments to test their hypothesis.",
    urduExample: "سائنسدانوں نے اپنے مفروضے کی جانچ کے لیے تجربات کیے۔",
    synonyms: ["Theory", "Premise", "Assumption"]
  },
  {
    id: 36,
    word: "Acquire",
    phonetic: "/əˈkwaɪər/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Education",
    urduMeaning: "حاصل کرنا، سیکھنا، پانا",
    englishExample: "Reading books helps you acquire vast knowledge.",
    urduExample: "کتابیں پڑھنے سے آپ وسیع علم حاصل کرتے ہیں۔",
    synonyms: ["Gain", "Obtain", "Attain"]
  },
  {
    id: 37,
    word: "Profound",
    phonetic: "/prəˈfaʊnd/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Education",
    urduMeaning: "گہرا، بصیرت افروز، بااثر",
    englishExample: "The teacher's advice had a profound impact on my life.",
    urduExample: "استاد کی نصیحت کا میری زندگی پر گہرا اثر پڑا۔",
    synonyms: ["Deep", "Insightful", "Intense"]
  },
  {
    id: 38,
    word: "Evaluate",
    phonetic: "/ɪˈvæl.ju.eɪt/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Education",
    urduMeaning: "جانچنا، تخمینہ لگانا، جائزہ لینا",
    englishExample: "The examiner will evaluate your paper carefully.",
    urduExample: "ممتحن آپ کے پرچے کا بغور جائزہ لے گا۔",
    synonyms: ["Assess", "Appraise", "Judge"]
  },
  {
    id: 39,
    word: "Illustrate",
    phonetic: "/ˈɪl.ə.streɪt/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Education",
    urduMeaning: "مثال کے ذریعے واضح کرنا، تصویر بنانا",
    englishExample: "He used real-world examples to illustrate the concept.",
    urduExample: "اس نے تصور کو واضح کرنے کے لیے حقیقی زندگی کی مثالیں پیش کیں۔",
    synonyms: ["Explain", "Demonstrate", "Clarify"]
  },
  {
    id: 40,
    word: "Knowledgeable",
    phonetic: "/ˈnɒl.ɪ.dʒə.bəl/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Education",
    urduMeaning: "باخبر، صاحبِ علم، باصلاحیت",
    englishExample: "She is extremely knowledgeable about history.",
    urduExample: "وہ تاریخ کے بارے میں وسیع علم رکھتی ہے۔",
    synonyms: ["Educated", "Informed", "Scholarly"]
  },
  {
    id: 41,
    word: "Pedagogy",
    phonetic: "/ˈped.ə.ɡɒdʒ.i/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Education",
    urduMeaning: "تدریس کا علم و ہنر، طریقہ تعلیم",
    englishExample: "Modern pedagogy emphasizes student-centered learning.",
    urduExample: "جدید تدریسی نظام میں طالب علم کی عملی شرکت پر زور دیا جاتا ہے۔",
    synonyms: ["Teaching method", "Instruction", "Education"]
  },
  {
    id: 42,
    word: "Rigorous",
    phonetic: "/ˈrɪɡ.ər.əs/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Education",
    urduMeaning: "سخت، کڑا، مکمل جانچ پڑتال والا",
    englishExample: "Medical training requires rigorous practice.",
    urduExample: "طبی تربیت کے لیے سخت اور مسلسل مشق کی ضرورت ہوتی ہے۔",
    synonyms: ["Strict", "Stringent", "Demanding"]
  },

  // ==========================================
  // 5. WORK, BUSINESS & CAREER (دفتر، کاروبار و ملازمت)
  // ==========================================
  {
    id: 43,
    word: "Collaborate",
    phonetic: "/kəˈlæb.ə.reɪt/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Work & Business",
    urduMeaning: "مل کر کام کرنا، باہمی تعاون کرنا",
    englishExample: "The two companies decided to collaborate on the project.",
    urduExample: "دونوں کمپنیوں نے پروجیکٹ پر باہمی تعاون سے کام کرنے کا فیصلہ کیا۔",
    synonyms: ["Cooperates", "Partner", "Team up"]
  },
  {
    id: 44,
    word: "Negotiate",
    phonetic: "/nəˈɡoʊ.ʃi.eɪt/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Work & Business",
    urduMeaning: "بات چیت کرنا، سودے بازی کرنا، سمجھوتہ طے کرنا",
    englishExample: "They met to negotiate the terms of the business deal.",
    urduExample: "وہ کاروباری معاہدے کی شرائط طے کرنے کے لیے ملے۔",
    synonyms: ["Bargain", "Discuss", "Settle"]
  },
  {
    id: 45,
    word: "Feasible",
    phonetic: "/ˈfiː.zə.bəl/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Work & Business",
    urduMeaning: "ممکن، قابلِ عمل، عملی",
    englishExample: "We need to check if this business proposal is feasible.",
    urduExample: "ہمیں دیکھنا ہوگا کہ آیا یہ تجارتی تجویز قابلِ عمل ہے یا نہیں۔",
    synonyms: ["Practicable", "Viable", "Achievable"]
  },
  {
    id: 46,
    word: "Deadline",
    phonetic: "/ˈded.laɪn/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Work & Business",
    urduMeaning: "کام مکمل کرنے کی آخری تاریخ یا وقت",
    englishExample: "We must submit the financial report before the deadline.",
    urduExample: "ہمیں مالیاتی رپورٹ آخری وقت سے پہلے جمع کروانی ہوگی۔",
    synonyms: ["Due date", "Target date", "Limit"]
  },
  {
    id: 47,
    word: "Productivity",
    phonetic: "/ˌprɒd.ʌkˈtɪv.ə.ti/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Work & Business",
    urduMeaning: "پیداواری صلاحیت، کارکردگی",
    englishExample: "A good working environment boosts employee productivity.",
    urduExample: "ایک اچھا دفتری ماحول ملازمین کی کارکردگی اور پیداواری صلاحیت کو بڑھاتا ہے۔",
    synonyms: ["Efficiency", "Output", "Performance"]
  },
  {
    id: 48,
    word: "Strategy",
    phonetic: "/ˈstræt.ə.dʒi/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Work & Business",
    urduMeaning: "حکمتِ عملی، لائحہ عمل",
    englishExample: "A clear marketing strategy is necessary for sales growth.",
    urduExample: "فروخت میں اضافے کے لیے ایک واضح مارکیٹنگ حکمتِ عملی ضروری ہے۔",
    synonyms: ["Plan", "Tactics", "Scheme"]
  },
  {
    id: 49,
    word: "Entrepreneur",
    phonetic: "/ˌɒn.trə.prəˈnɜːr/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Work & Business",
    urduMeaning: "کاروباری شخص، نیا کاروبار شروع کرنے والا",
    englishExample: "The young entrepreneur launched a tech startup.",
    urduExample: "نوجوان کاروباری نے ایک ٹیکنالوجی اسٹارٹ اپ کا آغاز کیا۔",
    synonyms: ["Businessperson", "Founder", "Innovator"]
  },
  {
    id: 50,
    word: "Delegation",
    phonetic: "/ˌdel.ɪˈɡeɪ.ʃən/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Work & Business",
    urduMeaning: "اختیار سونپنا، کام دوسروں کے سپرد کرنا، وفد",
    englishExample: "Effective delegation makes a manager far more successful.",
    urduExample: "کام کی درست تقسیم اور سونپنا مینیجر کو زیادہ کامیاب بناتا ہے۔",
    synonyms: ["Assignment", "Entrustment", "Transfer"]
  },
  {
    id: 51,
    word: "Revenue",
    phonetic: "/ˈrev.ən.juː/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Work & Business",
    urduMeaning: "آمدنی، محاصل، کل وصولیاں",
    englishExample: "The company reported a 25% increase in annual revenue.",
    urduExample: "کمپنی نے سالانہ آمدنی میں 25 فیصد اضافے کی رپورٹ پیش کی۔",
    synonyms: ["Income", "Earnings", "Proceeds"]
  },
  {
    id: 52,
    word: "Synergy",
    phonetic: "/ˈsɪn.ə.dʒi/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Work & Business",
    urduMeaning: "مشترکہ قوت، مل کر کام کرنے سے پیدا ہونے والا باہمی اثر",
    englishExample: "The synergy between sales and tech teams drove remarkable results.",
    urduExample: "سیلز اور ٹیکنالوجی ٹیموں کے باہمی اشتراک نے شاندار نتائج دیے۔",
    synonyms: ["Cooperation", "Teamwork", "Alliance"]
  },

  // ==========================================
  // 6. HEALTH, WELLNESS & FITNESS (صحت، جسم اور تندرستی)
  // ==========================================
  {
    id: 53,
    word: "Immunity",
    phonetic: "/ɪˈmjuː.nə.ti/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Health & Fitness",
    urduMeaning: "قوتِ مدافعت، بیماری سے بچاؤ کی طاقت",
    englishExample: "Fresh fruits and vegetables strengthen your immunity.",
    urduExample: "تازہ پھل اور سبزیاں آپ کی قوتِ مدافعت کو مضبوط بناتے ہیں۔",
    synonyms: ["Resistance", "Defense", "Protection"]
  },
  {
    id: 54,
    word: "Sedentary",
    phonetic: "/ˈsed.ən.tər.i/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Health & Fitness",
    urduMeaning: "بیٹھے رہنے والا، بے حرکت طرز زندگی",
    englishExample: "A sedentary lifestyle causes several health problems.",
    urduExample: "سارا دن بیٹھے رہنے کا سست اندازِ زندگی کئی امراض کا سبب بنتا ہے۔",
    synonyms: ["Inactive", "Sluggish", "Desk-bound"]
  },
  {
    id: 55,
    word: "Nourishment",
    phonetic: "/ˈnʌr.ɪʃ.mənt/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Health & Fitness",
    urduMeaning: "غذائیت، پرورش، بالیدگی",
    englishExample: "Growing children need balanced nourishment.",
    urduExample: "بڑھتے ہوئے بچوں کو متوازن غذائیت کی ضرورت ہوتی ہے۔",
    synonyms: ["Nutrition", "Food", "Sustenance"]
  },
  {
    id: 56,
    word: "Chronic",
    phonetic: "/ˈkrɒn.ɪk/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Health & Fitness",
    urduMeaning: "دائمی، پرانا، دیرپا بیماری",
    englishExample: "He suffers from chronic back pain.",
    urduExample: "وہ کمر کے دائمی اور دیرینہ درد میں مبتلا ہے۔",
    synonyms: ["Persistent", "Long-term", "Enduring"]
  },
  {
    id: 57,
    word: "Fatigue",
    phonetic: "/fəˈtiːɡ/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Health & Fitness",
    urduMeaning: "تھکن، تکان، نقاہت",
    englishExample: "Proper sleep is the best remedy for mental fatigue.",
    urduExample: "مناسب نیند ذہنی تھکن کا بہترین علاج ہے۔",
    synonyms: ["Tiredness", "Exhaustion", "Weariness"]
  },
  {
    id: 58,
    word: "Hygiene",
    phonetic: "/ˈhaɪ.dʒiːn/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Health & Fitness",
    urduMeaning: "صفائی ستھرائی، حفظانِ صحت کے اصول",
    englishExample: "Good dental hygiene prevents tooth decay.",
    urduExample: "دانتوں کی اچھی صفائی ستھرائی دانتوں کو خراب ہونے سے بچاتی ہے۔",
    synonyms: ["Cleanliness", "Sanitation", "Purity"]
  },
  {
    id: 59,
    word: "Therapeutic",
    phonetic: "/ˌθer.əˈpjuː.tɪk/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Health & Fitness",
    urduMeaning: "شفابخش، علاج کا، راحت بخش",
    englishExample: "Listening to the sound of rain has a therapeutic effect.",
    urduExample: "بارش کی آواز سننا انسان پر شفابخش اور پرسکون اثر ڈالتا ہے۔",
    synonyms: ["Healing", "Curative", "Restorative"]
  },
  {
    id: 60,
    word: "Hydrate",
    phonetic: "/haɪˈdreɪt/",
    pos: "Verb (فعل)",
    level: "Beginner",
    category: "Health & Fitness",
    urduMeaning: "پانی کی کمی دور کرنا، جسم کو تر رکھنا",
    englishExample: "Drink plenty of fluids to hydrate your body in summer.",
    urduExample: "گرمیوں میں اپنے جسم میں پانی کی کمی دور کرنے کے لیے خوب پانی پیئیں۔",
    synonyms: ["Moisten", "Water", "Refresh"]
  },

  // ==========================================
  // 7. POWER ACTION VERBS (اہم اور پرتاثیر افعال)
  // ==========================================
  {
    id: 61,
    word: "Persevere",
    phonetic: "/ˌpɜː.sɪˈvɪər/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Action Verbs",
    urduMeaning: "ثابت قدم رہنا، ڈٹے رہنا، ہمت نہ ہارنا",
    englishExample: "You will succeed if you persevere through setbacks.",
    urduExample: "اگر آپ مشکلات میں ڈٹے رہیں گے تو ضرور کامیاب ہوں گے۔",
    synonyms: ["Persist", "Carry on", "Hold on"]
  },
  {
    id: 62,
    word: "Alleviate",
    phonetic: "/əˈliː.vi.eɪt/",
    pos: "Verb (فعل)",
    level: "Advanced",
    category: "Action Verbs",
    urduMeaning: "کم کرنا، تخفیف کرنا، تکلیف ہلکی کرنا",
    englishExample: "The medicine will help alleviate your pain.",
    urduExample: "یہ دوا آپ کے درد کو کم کرنے میں مدد دے گی۔",
    synonyms: ["Ease", "Relieve", "Lessen"]
  },
  {
    id: 63,
    word: "Articulate",
    phonetic: "/ɑːˈtɪk.jə.leɪt/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Action Verbs",
    urduMeaning: "واضح انداز میں بیان کرنا، صاف بولنا",
    englishExample: "She can articulate her ideas with great clarity.",
    urduExample: "وہ اپنے خیالات کو نہایت واضح اور پرتاثیر انداز میں بیان کر سکتی ہے۔",
    synonyms: ["Express", "Vocalize", "State"]
  },
  {
    id: 64,
    word: "Accomplish",
    phonetic: "/əˈkʌm.plɪʃ/",
    pos: "Verb (فعل)",
    level: "Beginner",
    category: "Action Verbs",
    urduMeaning: "مکمل کرنا، حاصل کرنا، پایہ تکمیل تک پہنچانا",
    englishExample: "Hard work allowed him to accomplish his goals.",
    urduExample: "محنت کے بل بوتے پر وہ اپنے مقاصد کو حاصل کرنے میں کامیاب رہا۔",
    synonyms: ["Achieve", "Fulfill", "Attain"]
  },
  {
    id: 65,
    word: "Diminish",
    phonetic: "/dɪˈmɪn.ɪʃ/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Action Verbs",
    urduMeaning: "گھٹنا، کم ہونا یا کرنا، زوال پذیر ہونا",
    englishExample: "The darkness diminished as the morning sun rose.",
    urduExample: "صبح کا سورج طلوع ہوتے ہی اندھیرا کم ہوتا چلا گیا۔",
    synonyms: ["Decrease", "Reduce", "Dwindle"]
  },
  {
    id: 66,
    word: "Enhance",
    phonetic: "/ɪnˈhɑːns/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Action Verbs",
    urduMeaning: "بڑھانا، نکھارنا، خوبصورت بنانا",
    englishExample: "Good lighting can enhance the beauty of any room.",
    urduExample: "اچھی روشنی کسی بھی کمرے کی خوبصورتی کو نکھار سکتی ہے۔",
    synonyms: ["Improve", "Boost", "Upgrade"]
  },
  {
    id: 67,
    word: "Implement",
    phonetic: "/ˈɪm.plɪ.ment/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Action Verbs",
    urduMeaning: "نافذ کرنا، لاگو کرنا، عملی جامہ پہنانا",
    englishExample: "The school decided to implement a new attendance system.",
    urduExample: "سکول نے حاضری کے نئے نظام کو نافذ کرنے کا فیصلہ کیا۔",
    synonyms: ["Execute", "Apply", "Enforce"]
  },
  {
    id: 68,
    word: "Exaggerate",
    phonetic: "/ɪɡˈzædʒ.ə.reɪt/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Action Verbs",
    urduMeaning: "بات بڑھا چڑھا کر پیش کرنا، مبالغہ آرائی کرنا",
    englishExample: "Don't exaggerate the problem; it's easy to solve.",
    urduExample: "مسئلے کو اتنا بڑھا چڑھا کر پیش نہ کریں؛ یہ آسانی سے حل ہو سکتا ہے۔",
    synonyms: ["Overstate", "Magnify", "Amplify"]
  },
  {
    id: 69,
    word: "Scrutinize",
    phonetic: "/ˈskruː.tɪ.naɪz/",
    pos: "Verb (فعل)",
    level: "Advanced",
    category: "Action Verbs",
    urduMeaning: "باریک بینی سے معائنہ کرنا، چھان بین کرنا",
    englishExample: "The auditor will scrutinize every transaction.",
    urduExample: "آڈیٹر ہر لین دین کی باریک بینی سے چھان بین کرے گا۔",
    synonyms: ["Inspect", "Examine", "Audit"]
  },
  {
    id: 70,
    word: "Facilitate",
    phonetic: "/fəˈsɪl.ɪ.teɪt/",
    pos: "Verb (فعل)",
    level: "Advanced",
    category: "Action Verbs",
    urduMeaning: "آسان بنانا، سہولت بہم پہنچانا",
    englishExample: "Modern technology helps facilitate global communication.",
    urduExample: "جدید ٹیکنالوجی عالمی رابطوں کو آسان بنانے میں مدد دیتی ہے۔",
    synonyms: ["Enable", "Assist", "Ease"]
  },

  // ==========================================
  // 8. DESCRIPTIVE ADJECTIVES (اوصاف و اوضاع)
  // ==========================================
  {
    id: 71,
    word: "Abundant",
    phonetic: "/əˈbʌn.dənt/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Descriptive",
    urduMeaning: "کثیر، وافر، کثرت سے موجود",
    englishExample: "The region is rich in abundant natural resources.",
    urduExample: "یہ خطہ وافر قدرتی وسائل سے مالامال ہے۔",
    synonyms: ["Plentiful", "Ample", "Copious"]
  },
  {
    id: 72,
    word: "Scarce",
    phonetic: "/skeəs/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Descriptive",
    urduMeaning: "نایاب، کم یاب، قلیل",
    englishExample: "Clean drinking water is scarce in many deserts.",
    urduExample: "بہت سے صحراؤں میں پینے کا صاف پانی نایاب اور قلیل ہے۔",
    synonyms: ["Rare", "Sparse", "Deficient"]
  },
  {
    id: 73,
    word: "Vivid",
    phonetic: "/ˈvɪv.ɪd/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Descriptive",
    urduMeaning: "روشن، واضح، چمکدار، زندہ",
    englishExample: "I still have vivid memories of my childhood village.",
    urduExample: "مجھے اب بھی اپنے بچپن کے گاؤں کی روشن اور واضح یادیں یاد ہیں۔",
    synonyms: ["Graphic", "Bright", "Clear"]
  },
  {
    id: 74,
    word: "Ambiguous",
    phonetic: "/æmˈbɪɡ.ju.əs/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Descriptive",
    urduMeaning: "مبہم، غیر واضح، ذومعنی",
    englishExample: "His instructions were ambiguous and caused confusion.",
    urduExample: "اس کی ہدایات مبہم تھیں جس کی وجہ سے الجھن پیدا ہوئی۔",
    synonyms: ["Vague", "Unclear", "Doubtful"]
  },
  {
    id: 75,
    word: "Crucial",
    phonetic: "/ˈkruː.ʃəl/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Descriptive",
    urduMeaning: "انتہائی اہم، نازک، فیصلہ کن",
    englishExample: "Good sleep is crucial for mental well-being.",
    urduExample: "ذہنی سکون اور صحت کے لیے اچھی نیند انتہائی اہم ہے۔",
    synonyms: ["Vital", "Critical", "Pivotal"]
  },
  {
    id: 76,
    word: "Inevitable",
    phonetic: "/ɪˈnev.ɪ.tə.bəl/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Descriptive",
    urduMeaning: "ناگزیر، اٹل، جس سے بچا نہ جا سکے",
    englishExample: "Change is an inevitable part of human life.",
    urduExample: "تبدیلی انسانی زندگی کا ایک ناگزیر اور اٹل حصہ ہے۔",
    synonyms: ["Unavoidable", "Certain", "Inescapable"]
  },
  {
    id: 77,
    word: "Fragile",
    phonetic: "/ˈfrædʒ.aɪl/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Descriptive",
    urduMeaning: "نازک، جلد ٹوٹ جانے والا، کمزور",
    englishExample: "Be careful with that fragile glass vase.",
    urduExample: "شیشے کے اس نازک گلدان کو سنبھال کر رکھیں۔",
    synonyms: ["Delicate", "Brittle", "Frail"]
  },
  {
    id: 78,
    word: "Magnificent",
    phonetic: "/mæɡˈnɪf.ɪ.sənt/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Descriptive",
    urduMeaning: "شاندار، عالیشان، پرشکوہ",
    englishExample: "The historical fort offers a magnificent view of the valley.",
    urduExample: "تاریخی قلعہ وادی کا شاندار اور پرشکوہ منظر پیش کرتا ہے۔",
    synonyms: ["Splendid", "Grand", "Superb"]
  },
  {
    id: 79,
    word: "Obsolete",
    phonetic: "/ˌɒb.səˈliːt/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Descriptive",
    urduMeaning: "متروک، پرانا، غیر مستعمل",
    englishExample: "Floppy disks have become completely obsolete.",
    urduExample: "فلاپی ڈسک اب مکمل طور پر متروک ہو چکی ہیں۔",
    synonyms: ["Outdated", "Archaic", "Antique"]
  },
  {
    id: 80,
    word: "Intricate",
    phonetic: "/ˈɪn.trɪ.kət/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Descriptive",
    urduMeaning: "پیچیدہ، باریک، الجھا ہوا",
    englishExample: "The carpet had an intricate and detailed pattern.",
    urduExample: "قالین پر ایک پیچیدہ اور نہایت باریک ڈیزائن بنا ہوا تھا۔",
    synonyms: ["Complex", "Elaborate", "Detailed"]
  },

  // ==========================================
  // 9. IDIOMS & PHRASES (اہم محاورات و روزمرہ اصطلاحات)
  // ==========================================
  {
    id: 81,
    word: "A blessing in disguise",
    phonetic: "/ə ˈbles.ɪŋ ɪn dɪsˈɡaɪz/",
    pos: "Idiom (محاورہ)",
    level: "Intermediate",
    category: "Idioms",
    urduMeaning: "ظاہری نقصان جو دراصل فائدے کا سبب بنے (زحمت میں رحمت)",
    englishExample: "Losing that bad job turned out to be a blessing in disguise.",
    urduExample: "اس خراب نوکری کا چھوٹنا دراصل زحمت میں رحمت ثابت ہوا۔",
    synonyms: ["Hidden benefit", "Fortunate turn"]
  },
  {
    id: 82,
    word: "Bite the bullet",
    phonetic: "/baɪt ðə ˈbʊl.ɪt/",
    pos: "Idiom (محاورہ)",
    level: "Intermediate",
    category: "Idioms",
    urduMeaning: "کسی ناگوار یا مشکل کام کو بہادری سے برداشت کرنا یا کر گزرنا",
    englishExample: "I had to bite the bullet and apologize for my mistake.",
    urduExample: "مجھے اپنی انا مار کر اپنی غلطی کی معافی مانگنی ہی پڑی۔",
    synonyms: ["Face the music", "Endure"]
  },
  {
    id: 83,
    word: "Burn the midnight oil",
    phonetic: "/bɜːn ðə ˈmɪd.naɪt ɔɪl/",
    pos: "Idiom (محاورہ)",
    level: "Intermediate",
    category: "Idioms",
    urduMeaning: "دیر رات تک محنت اور پڑھائی کرنا، راتیں جاگنا",
    englishExample: "He burned the midnight oil to pass the CSS examination.",
    urduExample: "اس نے سی ایس ایس کا امتحان پاس کرنے کے لیے راتیں جاگ کر محنت کی۔",
    synonyms: ["Work late", "Study hard"]
  },
  {
    id: 84,
    word: "Hit the nail on the head",
    phonetic: "/hɪt ðə neɪl ɒn ðə hed/",
    pos: "Idiom (محاورہ)",
    level: "Beginner",
    category: "Idioms",
    urduMeaning: "بالکل صحیح اور ٹھیک بات کہنا، نشانے پر بیٹھنا",
    englishExample: "You hit the nail on the head with your analysis.",
    urduExample: "آپ نے اپنے تجزیے میں بالکل ٹھیک اور کھری بات کہی۔",
    synonyms: ["Accurate", "Exact point"]
  },
  {
    id: 85,
    word: "Piece of cake",
    phonetic: "/piːs əv keɪk/",
    pos: "Idiom (محاورہ)",
    level: "Beginner",
    category: "Idioms",
    urduMeaning: "بہت ہی آسان کام، بچوں کا کھیل",
    englishExample: "The driving test was a piece of cake for him.",
    urduExample: "ڈرائیونگ ٹیسٹ اس کے لیے بچوں کا کھیل ثابت ہوا۔",
    synonyms: ["Very easy", "Breeze", "Effortless"]
  },
  {
    id: 86,
    word: "Actions speak louder than words",
    phonetic: "/ˈæk.ʃənz spiːk ˈlaʊ.dər ðæn wɜːdz/",
    pos: "Proverb (ضرب المثل)",
    level: "Beginner",
    category: "Idioms",
    urduMeaning: "عمل باتوں سے زیادہ بولتا ہے، عملی ثبوت باتوں سے بہتر ہے",
    englishExample: "Don't just make promises; remember that actions speak louder than words.",
    urduExample: "صرف وعدے نہ کرو؛ یاد رکھو کہ عمل باتوں سے زیادہ وزن رکھتا ہے۔",
    synonyms: ["Practical proof", "Behavior counts"]
  },

  // ==========================================
  // 10. SOCIAL, SOCIETY & CULTURE (معاشرت اور قانون)
  // ==========================================
  {
    id: 87,
    word: "Harmony",
    phonetic: "/ˈhɑː.mə.ni/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Society",
    urduMeaning: "ہم آہنگی، باہمی اتحاد، یگانگت",
    englishExample: "People of different cultures live in harmony here.",
    urduExample: "مختلف ثقافتوں کے لوگ یہاں باہمی ہم آہنگی اور یگانگت کے ساتھ رہتے ہیں۔",
    synonyms: ["Peace", "Unity", "Accord"]
  },
  {
    id: 88,
    word: "Prejudice",
    phonetic: "/ˈpredʒ.ə.dɪs/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Society",
    urduMeaning: "تعصب، جانبداری، بلا سوچے سمجھے منفی رائے قائم کرنا",
    englishExample: "Education plays a big role in eliminating prejudice.",
    urduExample: "تعلیم تعصب کے خاتمے میں بہت بڑا کردار ادا کرتی ہے۔",
    synonyms: ["Bias", "Discrimination", "Bigotry"]
  },
  {
    id: 89,
    word: "Tolerance",
    phonetic: "/ˈtɒl.ər.əns/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Society",
    urduMeaning: "رواداری، برداشت، تحمل",
    englishExample: "Tolerance is essential for a peaceful society.",
    urduExample: "ایک پرامن معاشرے کے لیے رواداری اور برداشت لازمی ہے۔",
    synonyms: ["Patience", "Acceptance", "Endurance"]
  },
  {
    id: 90,
    word: "Philanthropy",
    phonetic: "/fɪˈlæn.θrə.pi/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Society",
    urduMeaning: "فلاحِ انسانیت، انسان دوستی، خیرات و صدقات",
    englishExample: "His philanthropy provided schools for thousands of poor children.",
    urduExample: "اس کی انسان دوستی اور فلاحی کاموں نے ہزاروں غریب بچوں کو سکول فراہم کیے۔",
    synonyms: ["Charity", "Altruism", "Generosity"]
  },
  {
    id: 91,
    word: "Heritage",
    phonetic: "/ˈher.ɪ.tɪdʒ/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Society",
    urduMeaning: "ورثہ، تاریخی و ثقافتی ترکہ",
    englishExample: "We must preserve our rich cultural heritage.",
    urduExample: "ہمیں اپنے شاندار ثقافتی ورثے کا تحفظ کرنا چاہیے۔",
    synonyms: ["Legacy", "Tradition", "Inheritance"]
  },
  {
    id: 92,
    word: "Integrity",
    phonetic: "/ɪnˈteɡ.rə.ti/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Society",
    urduMeaning: "سالمیت، کھراپن، دیانت داری اور اصول پسندی",
    englishExample: "A judge must be a person of undeniable integrity.",
    urduExample: "ایک جج کو ناقابلِ تردید دیانت داری اور اصول پسندی کا پیکر ہونا چاہیے۔",
    synonyms: ["Honesty", "Morality", "Uprightness"]
  },

  // ==========================================
  // 11. NATURE, ENVIRONMENT & WEATHER (فطرت، ماحول و موسم)
  // ==========================================
  {
    id: 93,
    word: "Serene",
    phonetic: "/səˈriːn/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Nature",
    urduMeaning: "پرسکون، پرامن، ٹھنڈا اور دلکش",
    englishExample: "The lake looked serene under the morning mist.",
    urduExample: "صبح کی دھند میں جھیل کا منظر نہایت پرسکون اور دلکش لگ رہا تھا۔",
    synonyms: ["Tranquil", "Calm", "Peaceful"]
  },
  {
    id: 94,
    word: "Torrential",
    phonetic: "/təˈren.ʃəl/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Nature",
    urduMeaning: "موسلادھار، تند و تیز (بارش یا سیلاب)",
    englishExample: "Torrential rain flooded the city streets within hours.",
    urduExample: "موسلادھار بارش نے چند گھنٹوں میں شہر کی سڑکیں زیرِ آب کر دیں۔",
    synonyms: ["Pouring", "Deluging", "Heavy"]
  },
  {
    id: 95,
    word: "Breeze",
    phonetic: "/briːz/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Nature",
    urduMeaning: "بادِ نسیم، ہلکی اور ٹھنڈی ہوا کا جھونکا",
    englishExample: "A cool breeze was blowing across the seashore.",
    urduExample: "سمندر کے کنارے ایک ٹھنڈی اور خوشگوار ہوا چل رہی تھی۔",
    synonyms: ["Wind", "Draft", "Zephyr"]
  },
  {
    id: 96,
    word: "Biodiversity",
    phonetic: "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Nature",
    urduMeaning: "حیاتیاتی تنوع، جانوروں اور پودوں کی مختلف اقسام",
    englishExample: "Tropical rainforests have incredible biodiversity.",
    urduExample: "استوائی بارانی جنگلات میں حیرت انگیز حیاتیاتی تنوع پایا جاتا ہے۔",
    synonyms: ["Ecological variety", "Wildlife diversity"]
  },
  {
    id: 97,
    word: "Scenic",
    phonetic: "/ˈsiː.nɪk/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Nature",
    urduMeaning: "خوبصورت قدرتی مناظر والا، دل فریب",
    englishExample: "We drove along the scenic northern mountain route.",
    urduExample: "ہم نے شمالی پہاڑی راستے کے دل فریب مناظر کے ساتھ سفر کیا۔",
    synonyms: ["Picturesque", "Breathtaking", "Beautiful"]
  },

  // ==========================================
  // 12. ADVANCED ACADEMIC & INTELLECTUAL (اعلیٰ علمی و فکری الفاظ)
  // ==========================================
  {
    id: 98,
    word: "Pragmatic",
    phonetic: "/præɡˈmæt.ɪk/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Education",
    urduMeaning: "حقیقت پسندانہ، عملی سوچ رکھنے والا",
    englishExample: "We need a pragmatic solution rather than theoretical debate.",
    urduExample: "ہمیں نظریاتی بحث کی بجائے ایک عملی اور حقیقت پسندانہ حل کی ضرورت ہے۔",
    synonyms: ["Practical", "Realistic", "Sensible"]
  },
  {
    id: 99,
    word: "Paradox",
    phonetic: "/ˈpær.ə.dɒks/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Education",
    urduMeaning: "تضاد، بظاہر الٹی مگر درحقیقت سچی بات",
    englishExample: "It is a paradox that technology connects the world yet divides people.",
    urduExample: "یہ ایک عجیب تضاد ہے کہ ٹیکنالوجی نے دنیا کو جوڑا بھی ہے اور انسانوں کو دور بھی کیا ہے۔",
    synonyms: ["Contradiction", "Puzzle", "Enigma"]
  },
  {
    id: 100,
    word: "Ambiguity",
    phonetic: "/ˌæm.bɪˈɡjuː.ə.ti/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Education",
    urduMeaning: "ابہام، التباس، دو مفہوم ہونا",
    englishExample: "The contract was written clearly to leave no room for ambiguity.",
    urduExample: "معاہدہ اتنی وضاحت سے لکھا گیا تھا کہ ابہام کی کوئی گنجائش نہ رہے۔",
    synonyms: ["Unclarity", "Vagueness", "Equivocation"]
  },
  {
    id: 101,
    word: "Ubiquitous",
    phonetic: "/juːˈbɪk.wɪ.təs/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Descriptive",
    urduMeaning: "ہر جگہ موجود، ہمہ گیر، ہر سُو حاضر",
    englishExample: "Smartphones have become ubiquitous in modern society.",
    urduExample: "جدید معاشرے میں اسمارٹ فونز ہر جگہ عام اور ہمہ گیر ہو چکے ہیں۔",
    synonyms: ["Omnipresent", "Everywhere", "Pervasive"]
  },
  {
    id: 102,
    word: "Ephemeral",
    phonetic: "/ɪˈfem.ər.əl/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Descriptive",
    urduMeaning: "عارضی، چند روزہ، فانی، جلد مٹ جانے والا",
    englishExample: "Fame and worldly glory are often ephemeral.",
    urduExample: "شہرت اور دنیاوی شان و شوکت اکثر عارضی اور فانی ہوتی ہے۔",
    synonyms: ["Fleeting", "Transient", "Short-lived"]
  },
  {
    id: 103,
    word: "Lucid",
    phonetic: "/ˈluː.sɪd/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Education",
    urduMeaning: "واضح، شفاف، آسانی سے سمجھ میں آنے والا",
    englishExample: "The professor gave a lucid explanation of quantum physics.",
    urduExample: "پروفیسر نے کوانٹم فزکس کی نہایت واضح اور آسان وضاحت پیش کی۔",
    synonyms: ["Clear", "Coherent", "Luminous"]
  },
  {
    id: 104,
    word: "Tenacious",
    phonetic: "/təˈneɪ.ʃəs/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "مستقل مزاج، مضبوط گرفت والا، پختہ عزم",
    englishExample: "Her tenacious pursuit of justice earned her high respect.",
    urduExample: "انصاف کے حصول میں اس کی انتھک اور پختہ کوششوں نے اسے بڑا احترام دلایا۔",
    synonyms: ["Persistent", "Determined", "Steadfast"]
  },
  {
    id: 105,
    word: "Authentic",
    phonetic: "/ɔːˈθen.tɪk/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Descriptive",
    urduMeaning: "اصلی، مستند، خالص، کھرا",
    englishExample: "Always buy authentic products to avoid fraud.",
    urduExample: "دھوکے سے بچنے کے لیے ہمیشہ اصلی اور مستند اشیاء خریدیں۔",
    synonyms: ["Genuine", "Real", "Legitimate"]
  },
  {
    id: 106,
    word: "Optimistic",
    phonetic: "/ˌɒp.tɪˈmɪs.tɪk/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Personality",
    urduMeaning: "پُر امید، مثبت سوچ رکھنے والا، رجائیت پسند",
    englishExample: "She remains optimistic about her future success.",
    urduExample: "وہ اپنی مستقبل کی کامیابی کے بارے میں ہمیشہ پرامید رہتی ہے۔",
    synonyms: ["Hopeful", "Positive", "Confident"]
  },
  {
    id: 107,
    word: "Pessimistic",
    phonetic: "/ˌpes.ɪˈmɪs.tɪk/",
    pos: "Adjective (صفت)",
    level: "Beginner",
    category: "Personality",
    urduMeaning: "مایوس کن، منفی پہلو دیکھنے والا، قنوطیت پسند",
    englishExample: "Do not adopt a pessimistic view of your life.",
    urduExample: "اپنی زندگی کے بارے میں مایوس کن اور منفی سوچ اختیار نہ کریں۔",
    synonyms: ["Gloomy", "Negative", "Defeatist"]
  },
  {
    id: 108,
    word: "Courteous",
    phonetic: "/ˈkɜː.ti.əs/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "خوش اخلاق، باادب، شائستہ",
    englishExample: "The staff members were friendly and courteous.",
    urduExample: "عملے کے ارکان دوستانہ اور نہایت خوش اخلاق و شائستہ تھے۔",
    synonyms: ["Polite", "Respectful", "Civil"]
  },
  {
    id: 109,
    word: "Procrastinate",
    phonetic: "/prəʊˈkræs.tɪ.neɪt/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Action Verbs",
    urduMeaning: "ٹال مٹول کرنا، کام میں تاخیر کرنا، کل پر ڈالنا",
    englishExample: "If you procrastinate, you will miss the application deadline.",
    urduExample: "اگر آپ ٹال مٹول کریں گے تو درخواست کی آخری تاریخ نکل جائے گی۔",
    synonyms: ["Delay", "Postpone", "Stall"]
  },
  {
    id: 110,
    word: "Consolidate",
    phonetic: "/kənˈsɒl.ɪ.deɪt/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Work & Business",
    urduMeaning: "مضبوط کرنا، یکجا کرنا، مجتمع کرنا",
    englishExample: "The bank aims to consolidate its position in the market.",
    urduExample: "بینک کا مقصد مارکیٹ میں اپنی پوزیشن کو مزید مستحکم اور مضبوط بنانا ہے۔",
    synonyms: ["Strengthen", "Combine", "Unify"]
  },
  {
    id: 111,
    word: "Nourish",
    phonetic: "/ˈnʌr.ɪʃ/",
    pos: "Verb (فعل)",
    level: "Beginner",
    category: "Health & Fitness",
    urduMeaning: "پرورش کرنا، کھلانا پلانا، غذا دینا",
    englishExample: "A loving family nourishes a child's soul.",
    urduExample: "ایک محبت کرنے والا خاندان بچے کی روح کو پروان چڑھاتا ہے۔",
    synonyms: ["Feed", "Nurture", "Sustain"]
  },
  {
    id: 112,
    word: "Spontaneous",
    phonetic: "/spɒnˈteɪ.ni.əs/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "بے ساختہ، فی البدیہہ، خود بخود ہونے والا",
    englishExample: "The crowd broke into spontaneous applause.",
    urduExample: "حاضرین نے بے ساختہ تالیاں بجانا شروع کر دیں۔",
    synonyms: ["Impulsive", "Unplanned", "Natural"]
  },
  {
    id: 113,
    word: "Impartial",
    phonetic: "/ɪmˈpɑː.ʃəl/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Society",
    urduMeaning: "غیر جانبدار، منصفانہ، بلا امتیاز",
    englishExample: "An umpire must remain completely impartial.",
    urduExample: "ایک امپائر کو مکمل طور پر غیر جانبدار رہنا چاہیے۔",
    synonyms: ["Unbiased", "Neutral", "Fair"]
  },
  {
    id: 114,
    word: "Vulnerable",
    phonetic: "/ˈvʌl.nər.ə.bəl/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Descriptive",
    urduMeaning: "غیر محفوظ، کمزور، خطرے کی زد میں",
    englishExample: "Elderly people are more vulnerable to winter illnesses.",
    urduExample: "بزرگ افراد سردیوں کی بیماریوں کے سامنے زیادہ کمزور اور خطرے میں ہوتے ہیں۔",
    synonyms: ["Susceptible", "Defenseless", "Exposed"]
  },
  {
    id: 115,
    word: "Resign",
    phonetic: "/rɪˈzaɪn/",
    pos: "Verb (فعل)",
    level: "Beginner",
    category: "Work & Business",
    urduMeaning: "استعفیٰ دینا، دستبردار ہونا",
    englishExample: "He decided to resign from his job for personal reasons.",
    urduExample: "اس نے ذاتی وجوہات کی بنا پر اپنی نوکری سے استعفیٰ دینے کا فیصلہ کیا۔",
    synonyms: ["Step down", "Quit", "Relinquish"]
  },
  {
    id: 116,
    word: "Gratitude",
    phonetic: "/ˈɡræt.ɪ.tʃuːd/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Emotions",
    urduMeaning: "شکر گزاری، احسان مندی، سپاس",
    englishExample: "He expressed his sincere gratitude to his teachers.",
    urduExample: "اس نے اپنے اساتذہ کا تہہ دل سے شکر اور احسان مندی کا اظہار کیا۔",
    synonyms: ["Thankfulness", "Appreciation", "Recognition"]
  },
  {
    id: 117,
    word: "Apprehension",
    phonetic: "/ˌæp.rɪˈhen.ʃən/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Emotions",
    urduMeaning: "خوف، خدشہ، وسوسہ، دھڑکا",
    englishExample: "She stepped onto the stage with slight apprehension.",
    urduExample: "وہ ہلکے سے خدشے اور وسوسے کے ساتھ اسٹیج پر چڑھی۔",
    synonyms: ["Dread", "Unease", "Anxiety"]
  },
  {
    id: 118,
    word: "Compassion",
    phonetic: "/kəmˈpæʃ.ən/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Emotions",
    urduMeaning: "رحم دلی، شفقت، درد مندی",
    englishExample: "True greatness lies in showing compassion to those in need.",
    urduExample: "سچی بڑائی ضرورت مندوں پر رحم اور شفقت کرنے میں پنہاں ہے۔",
    synonyms: ["Sympathy", "Kindness", "Mercy"]
  },
  {
    id: 119,
    word: "Versatile",
    phonetic: "/ˈvɜː.sə.taɪl/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "ہمہ جہت، ہر فن مولا، کثیر المقاصد",
    englishExample: "He is a versatile actor who can play comedy and drama equally well.",
    urduExample: "وہ ایک ہمہ جہت اداکار ہے جو مزاح اور سنجیدہ اداکاری یکساں مہارت سے نبھاتا ہے۔",
    synonyms: ["Adaptable", "Multifaceted", "Resourceful"]
  },
  {
    id: 120,
    word: "Subtle",
    phonetic: "/ˈsʌt.əl/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Descriptive",
    urduMeaning: "لطیف، باریک، جو آسانی سے نظر نہ آئے",
    englishExample: "There is a subtle difference between the two colors.",
    urduExample: "دونوں رنگوں کے درمیان ایک باریک اور لطیف سا فرق ہے۔",
    synonyms: ["Delicate", "Faint", "Understated"]
  },
  {
    id: 121,
    word: "Ponder",
    phonetic: "/ˈpɒn.dər/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Action Verbs",
    urduMeaning: "غور و خوض کرنا، سوچ بچار کرنا",
    englishExample: "He sat by the window to ponder his future options.",
    urduExample: "وہ کھڑکی کے پاس بیٹھ کر اپنے مستقبل کے امکانات پر غور و خوض کرنے لگا۔",
    synonyms: ["Contemplate", "Reflect", "Meditate"]
  },
  {
    id: 122,
    word: "Deteriorate",
    phonetic: "/dɪˈtɪə.ri.ə.reɪt/",
    pos: "Verb (فعل)",
    level: "Advanced",
    category: "Action Verbs",
    urduMeaning: "بگڑنا، خراب ہونا، حالت بدتر ہونا",
    englishExample: "The weather began to deteriorate rapidly in the evening.",
    urduExample: "شام کے وقت موسم تیزی سے بگڑنا شروع ہو گیا۔",
    synonyms: ["Worsen", "Degrade", "Decline"]
  },
  {
    id: 123,
    word: "Authenticity",
    phonetic: "/ˌɔː.θenˈtɪs.ə.ti/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Society",
    urduMeaning: "اصلیت، سچائی، سند، صداقت",
    englishExample: "The museum verified the authenticity of the ancient manuscript.",
    urduExample: "عجائب گھر نے قدیم قلمی نسخے کی اصلیت اور صداقت کی تصدیق کی۔",
    synonyms: ["Genuineness", "Validity", "Truth"]
  },
  {
    id: 124,
    word: "Frugal",
    phonetic: "/ˈfruː.ɡəl/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Daily Life",
    urduMeaning: "کفایت شعار، کم خرچ، دیکھ بھال کر خرچ کرنے والا",
    englishExample: "He lives a frugal life and saves most of his income.",
    urduExample: "وہ کفایت شعارانہ زندگی بسر کرتا ہے اور اپنی زیادہ تر کمائی بچا لیتا ہے۔",
    synonyms: ["Thrifty", "Economical", "Sparing"]
  },
  {
    id: 125,
    word: "Benevolent",
    phonetic: "/bəˈnev.əl.ənt/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "خیر خواہ، مہربان، فیض رساں",
    englishExample: "The benevolent king was loved by all his subjects.",
    urduExample: "مہربان اور خیر خواہ بادشاہ سے اس کی تمام رعایا محبت کرتی تھی۔",
    synonyms: ["Kind", "Generous", "Charitable"]
  },
  {
    id: 126,
    word: "Reluctant",
    phonetic: "/rɪˈlʌk.tənt/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Emotions",
    urduMeaning: "ہچکچانے والا، نالان، بدلی سے راضی ہونے والا",
    englishExample: "He was reluctant to share his personal phone number.",
    urduExample: "وہ اپنا ذاتی فون نمبر دینے میں ہچکچاہٹ محسوس کر رہا تھا۔",
    synonyms: ["Hesitant", "Unwilling", "Averse"]
  },
  {
    id: 127,
    word: "Enthusiasm",
    phonetic: "/ɪnˈθjuː.zi.æz.əm/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Emotions",
    urduMeaning: "جوش و خروش، ولولہ، لگن",
    englishExample: "The students participated in the sports day with immense enthusiasm.",
    urduExample: "طلبہ نے کھیلوں کے دن بے پناہ جوش و خروش کے ساتھ حصہ لیا۔",
    synonyms: ["Zeal", "Passion", "Eagerness"]
  },
  {
    id: 128,
    word: "Overcome",
    phonetic: "/ˌəʊ.vəˈkʌm/",
    pos: "Verb (فعل)",
    level: "Beginner",
    category: "Action Verbs",
    urduMeaning: "قابو پانا، فتح حاصل کرنا، قابو میں لانا",
    englishExample: "You must overcome your fear of public speaking.",
    urduExample: "آپ کو لوگوں کے سامنے بولنے کے خوف پر قابو پانا ہوگا۔",
    synonyms: ["Conquer", "Surmount", "Defeat"]
  },
  {
    id: 129,
    word: "Prosperity",
    phonetic: "/prɒsˈper.ə.ti/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Work & Business",
    urduMeaning: "خوشحالی، کامیابی، فارغ البالی",
    englishExample: "Education and peace lead to economic prosperity.",
    urduExample: "تعلیم اور امن معاشی خوشحالی کی طرف لے جاتے ہیں۔",
    synonyms: ["Affluence", "Wealth", "Success"]
  },
  {
    id: 130,
    word: "Preposterous",
    phonetic: "/prɪˈpɒs.tər.əs/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Descriptive",
    urduMeaning: "بے ہودہ، مضحکہ خیز، عقل کے خلاف",
    englishExample: "The allegation against him was completely preposterous.",
    urduExample: "اس کے خلاف لگایا گیا الزام بالکل بے ہودہ اور عقل کے خلاف تھا۔",
    synonyms: ["Absurd", "Ridiculous", "Nonsensical"]
  },
  {
    id: 131,
    word: "Harmonious",
    phonetic: "/hɑːˈməʊ.ni.əs/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Society",
    urduMeaning: "ہم آہنگ، باہم میل جول والا، خوشگوار",
    englishExample: "They maintain a harmonious relationship with their neighbors.",
    urduExample: "وہ اپنے پڑوسیوں کے ساتھ ایک ہم آہنگ اور خوشگوار تعلق قائم رکھتے ہیں۔",
    synonyms: ["Peaceful", "Congenial", "Compatible"]
  },
  {
    id: 132,
    word: "Calamity",
    phonetic: "/kəˈlæm.ə.ti/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Nature",
    urduMeaning: "آفت، مصیبت، بلا، سانحہ",
    englishExample: "The earthquake was a terrible calamity for the region.",
    urduExample: "زلزلہ اس خطے کے لیے ایک خوفناک آفت اور سانحہ تھا۔",
    synonyms: ["Disaster", "Catastrophe", "Tragedy"]
  },
  {
    id: 133,
    word: "Prudent",
    phonetic: "/ˈpruː.dənt/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "دانش مند، ہوشیار، دور اندیش",
    englishExample: "It is prudent to save money for unexpected emergencies.",
    urduExample: "ناگہانی ہنگامی حالات کے لیے رقم بچا کر رکھنا دانشمندی ہے۔",
    synonyms: ["Wise", "Sensible", "Cautious"]
  },
  {
    id: 134,
    word: "Reconcile",
    phonetic: "/ˈrek.ən.saɪl/",
    pos: "Verb (فعل)",
    level: "Advanced",
    category: "Society",
    urduMeaning: "صلح کرانا، راضی نامہ کرنا، مطابقت پیدا کرنا",
    englishExample: "The two brothers decided to reconcile their differences.",
    urduExample: "دونوں بھائیوں نے اپنے اختلافات مٹا کر صلح کرنے کا فیصلہ کیا۔",
    synonyms: ["Make peace", "Settle", "Harmonize"]
  },
  {
    id: 135,
    word: "Spurious",
    phonetic: "/ˈspjʊə.ri.əs/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Descriptive",
    urduMeaning: "جعلی، نقلی، جھوٹا، بے بنیاد",
    englishExample: "The police seized spurious medicine from the unregistered store.",
    urduExample: "پولیس نے غیر رجسٹرڈ اسٹور سے جعلی اور نقلی ادویات ضبط کر لیں۔",
    synonyms: ["Fake", "Bogus", "Counterfeit"]
  },
  {
    id: 136,
    word: "Venerable",
    phonetic: "/ˈven.ər.ə.bəl/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "قابلِ احترام، بزرگ، محترم و مکرم",
    englishExample: "The venerable scholar was greeted with deep reverence.",
    urduExample: "محترم اور بزرگ عالم دین کا گہرے احترام کے ساتھ استقبال کیا گیا۔",
    synonyms: ["Respected", "Revered", "Honored"]
  },
  {
    id: 137,
    word: "Vindicate",
    phonetic: "/ˈvɪn.dɪ.keɪt/",
    pos: "Verb (فعل)",
    level: "Advanced",
    category: "Action Verbs",
    urduMeaning: "بے گناہ ثابت کرنا، حق پر ثابت کرنا",
    englishExample: "New DNA evidence served to vindicate the accused man.",
    urduExample: "نئے ڈی این اے شواہد نے ملزم شخص کو بے گناہ ثابت کر دیا۔",
    synonyms: ["Exonerate", "Clear", "Acquit"]
  },
  {
    id: 138,
    word: "Underestimate",
    phonetic: "/ˌʌn.dəˈres.tɪ.meɪt/",
    pos: "Verb (فعل)",
    level: "Beginner",
    category: "Action Verbs",
    urduMeaning: "کمتر سمجھنا، تخمینہ کم لگانا",
    englishExample: "Never underestimate the power of regular practice.",
    urduExample: "روزانہ کی باقاعدہ مشق کی طاقت کو کبھی کمتر نہ سمجھیں۔",
    synonyms: ["Undervalue", "Belittle", "Minimize"]
  },
  {
    id: 139,
    word: "Zeal",
    phonetic: "/ziːl/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Emotions",
    urduMeaning: "جوش، ولولہ، گرمجوشی، سرگرمی",
    englishExample: "He worked with great zeal to complete the charity mission.",
    urduExample: "اس نے فلاحی مشن کو مکمل کرنے کے لیے زبردست جوش اور ولولے سے کام کیا۔",
    synonyms: ["Passion", "Ardor", "Eagerness"]
  },
  {
    id: 140,
    word: "Resolute",
    phonetic: "/ˈrez.ə.luːt/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "ثابت قدم، پرعزم، پکا ارادہ رکھنے والا",
    englishExample: "She remained resolute in her decision to pursue higher studies.",
    urduExample: "وہ اعلیٰ تعلیم حاصل کرنے کے اپنے فیصلے پر پختہ اور ثابت قدم رہی۔",
    synonyms: ["Determined", "Firm", "Unwavering"]
  },
  {
    id: 141,
    word: "Affable",
    phonetic: "/ˈæf.ə.bəl/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "خلیق، ملنسار، شیریں کلام، پیار سے پیش آنے والا",
    englishExample: "Our new manager is very affable and approachable.",
    urduExample: "ہمارا نیا مینیجر نہایت خلیق، خوش اخلاق اور بات کرنے میں آسان ہے۔",
    synonyms: ["Friendly", "Genial", "Amiable"]
  },
  {
    id: 142,
    word: "Discipline",
    phonetic: "/ˈdɪs.ə.plɪn/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Education",
    urduMeaning: "نظم و ضبط، ضابطہ اخلاق، خود پر قابو",
    englishExample: "Self-discipline is the bridge between goals and accomplishment.",
    urduExample: "خود پر نظم و ضبط ہی انسان کے مقاصد اور کامیابی کے درمیان پل ہے۔",
    synonyms: ["Control", "Order", "Regulation"]
  },
  {
    id: 143,
    word: "Aesthetic",
    phonetic: "/esˈθet.ɪk/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Descriptive",
    urduMeaning: "جمالیاتی، حسن شناس، خوبصورتی کا احساس رکھنے والا",
    englishExample: "The building was designed with great aesthetic appeal.",
    urduExample: "عمارت کو شاندار جمالیاتی حسن اور کشش کے ساتھ ڈیزائن کیا گیا تھا۔",
    synonyms: ["Artistic", "Tasteful", "Beautiful"]
  },
  {
    id: 144,
    word: "Benevolence",
    phonetic: "/bəˈnev.əl.əns/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "نیک خواہی، فیاضی، احسان، رحم دلی",
    englishExample: "His benevolence touched the hearts of many poor families.",
    urduExample: "اس کی فیاضی اور رحم دلی نے بہت سے غریب خاندانوں کے دلوں کو چھو لیا۔",
    synonyms: ["Kindness", "Goodwill", "Charity"]
  },
  {
    id: 145,
    word: "Complacent",
    phonetic: "/kəmˈpleɪ.sənt/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "بے فکر، خود پسند، اپنی موجودہ حالت پر مطمئن ہو کر غفلت برتنے والا",
    englishExample: "We cannot afford to become complacent about cybersecurity.",
    urduExample: "ہم سائبر سیکیورٹی کے معاملے میں غافل اور بے فکر ہونے کے متحمل نہیں ہو سکتے۔",
    synonyms: ["Smug", "Self-satisfied", "Careless"]
  },
  {
    id: 146,
    word: "Consequence",
    phonetic: "/ˈkɒn.sɪ.kwəns/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Education",
    urduMeaning: "نتیجہ، اثر، انجام",
    englishExample: "You must consider the long-term consequences of your decision.",
    urduExample: "آپ کو اپنے فیصلے کے دور رس نتائج اور انجام پر غور کرنا چاہیے۔",
    synonyms: ["Outcome", "Result", "Effect"]
  },
  {
    id: 147,
    word: "Depict",
    phonetic: "/dɪˈpɪkt/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Action Verbs",
    urduMeaning: "عکاسی کرنا، تصویر کھینچنا، بیان کرنا",
    englishExample: "The painting depicts rural life in historical Punjab.",
    urduExample: "یہ پینٹنگ تاریخی پنجاب کی دیہی زندگی کی عکاسی کرتی ہے۔",
    synonyms: ["Portray", "Represent", "Describe"]
  },
  {
    id: 148,
    word: "Diligence",
    phonetic: "/ˈdɪl.ɪ.dʒəns/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Personality",
    urduMeaning: "محنت، تندہی، جانفشانی",
    englishExample: "His diligence at work earned him a rapid promotion.",
    urduExample: "دفتر میں اس کی محنت اور تندہی نے اسے فوری ترقی دلوائی۔",
    synonyms: ["Industriousness", "Perseverance", "Care"]
  },
  {
    id: 149,
    word: "Exemplary",
    phonetic: "/ɪɡˈzem.plər.i/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "مثالی، قابلِ تقلید، نمونہ",
    englishExample: "The teacher praised him for his exemplary conduct.",
    urduExample: "استاد نے اس کے مثالی اور قابلِ تقلید رویے پر اس کی تعریف کی۔",
    synonyms: ["Model", "Praiseworthy", "Ideal"]
  },
  {
    id: 150,
    word: "Flourish",
    phonetic: "/ˈflʌr.ɪʃ/",
    pos: "Verb (فعل)",
    level: "Intermediate",
    category: "Nature",
    urduMeaning: "پھلنا پھولنا، ترقی پانا، عروج حاصل کرنا",
    englishExample: "Trade began to flourish along the ancient Silk Road.",
    urduExample: "قدیم شاہراہ ریشم پر تجارت پھلنا پھولنا اور ترقی پانا شروع ہو گئی۔",
    synonyms: ["Thrive", "Prosper", "Bloom"]
  },
  {
    id: 151,
    word: "Gravity",
    phonetic: "/ˈɡræv.ə.ti/",
    pos: "Noun (اسم)",
    level: "Beginner",
    category: "Education",
    urduMeaning: "کششِ ثقل (سائنس)؛ سنجیدگی و اہمیت (معاملات میں)",
    englishExample: "The minister explained the gravity of the economic situation.",
    urduExample: "وزیر نے معاشی صورتحال کی سنجیدگی اور اہمیت کو بیان کیا۔",
    synonyms: ["Seriousness", "Weight", "Solemnity"]
  },
  {
    id: 152,
    word: "Hierarchy",
    phonetic: "/ˈhaɪə.rɑː.ki/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Work & Business",
    urduMeaning: "سلسلہ مراتب، درجاتی نظام، عہدوں کی ترتیب",
    englishExample: "He rose rapidly through the corporate hierarchy.",
    urduExample: "وہ کمپنی کے درجاتی نظام اور عہدوں میں تیزی سے اوپر گیا۔",
    synonyms: ["Ranking", "Pecking order", "Ladder"]
  },
  {
    id: 153,
    word: "Impromptu",
    phonetic: "/ɪmˈprɒmp.tjuː/",
    pos: "Adjective / Adverb (صفت / متعلق فعل)",
    level: "Advanced",
    category: "Daily Life",
    urduMeaning: "برجستہ، بنا تیاری کے، موقع پر ہی",
    englishExample: "He delivered an impromptu speech that amazed everyone.",
    urduExample: "اس نے بغیر کسی تیاری کے برجستہ تقریر کی جس نے سب کو حیران کر دیا۔",
    synonyms: ["Unprepared", "Spontaneous", "Extempore"]
  },
  {
    id: 154,
    word: "Juxtapose",
    phonetic: "/ˌdʒʌk.stəˈpəʊz/",
    pos: "Verb (فعل)",
    level: "Advanced",
    category: "Education",
    urduMeaning: "تقابل کے لیے ساتھ ساتھ رکھنا، آمنے سامنے لا کر موازنہ کرنا",
    englishExample: "The poet juxtaposed sorrow and joy in the same verse.",
    urduExample: "شاعر نے ایک ہی شعر میں غم اور خوشی کو آمنے سامنے لا کر تقابل پیش کیا۔",
    synonyms: ["Compare", "Contrast", "Collocate"]
  },
  {
    id: 155,
    word: "Kinship",
    phonetic: "/ˈkɪn.ʃɪp/",
    pos: "Noun (اسم)",
    level: "Intermediate",
    category: "Society",
    urduMeaning: "رشتہ داری، قرابت، اپنائیت، یگانگت",
    englishExample: "He felt a deep sense of kinship with his fellow travelers.",
    urduExample: "اس نے اپنے ساتھی مسافروں کے ساتھ گہری اپنائیت اور یگانگت محسوس کی۔",
    synonyms: ["Relationship", "Affinity", "Bond"]
  },
  {
    id: 156,
    word: "Lethargic",
    phonetic: "/ləˈθɑː.dʒɪk/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Health & Fitness",
    urduMeaning: "سست، کاہل، بے دم، نقاہت زدہ",
    englishExample: "Hot weather often makes people feel lethargic.",
    urduExample: "شدید گرم موسم اکثر لوگوں کو سست اور بے دم بنا دیتا ہے۔",
    synonyms: ["Sluggish", "Lazy", "Inactive"]
  },
  {
    id: 157,
    word: "Magnanimous",
    phonetic: "/mæɡˈnæn.ɪ.məs/",
    pos: "Adjective (صفت)",
    level: "Advanced",
    category: "Personality",
    urduMeaning: "عالی ظرف، بلند حوصلہ، فراخ دل",
    englishExample: "The winner was magnanimous in victory and praised his opponent.",
    urduExample: "فاتح نے جیت میں اعلیٰ ظرفی دکھائی اور اپنے حریف کی تعریف کی۔",
    synonyms: ["Generous", "Noble", "Big-hearted"]
  },
  {
    id: 158,
    word: "Nominal",
    phonetic: "/ˈnɒm.ɪ.nəl/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Work & Business",
    urduMeaning: "برائے نام، معمولی، بہت کم",
    englishExample: "They charged only a nominal fee for admission.",
    urduExample: "انہوں نے داخلے کے لیے صرف برائے نام اور معمولی فیس لی۔",
    synonyms: ["Minimal", "Token", "Small"]
  },
  {
    id: 159,
    word: "Onus",
    phonetic: "/ˈəʊ.nəs/",
    pos: "Noun (اسم)",
    level: "Advanced",
    category: "Work & Business",
    urduMeaning: "ذمہ داری، بوجھ، بارِ ثبوت",
    englishExample: "The onus is on the management to ensure staff safety.",
    urduExample: "عملے کے تحفظ کو یقینی بنانے کی ذمہ داری انتظامیہ پر عائد ہوتی ہے۔",
    synonyms: ["Responsibility", "Burden", "Obligation"]
  },
  {
    id: 160,
    word: "Pivotal",
    phonetic: "/ˈpɪv.ə.təl/",
    pos: "Adjective (صفت)",
    level: "Intermediate",
    category: "Education",
    urduMeaning: "مرکزی، کلیدی، فیصلہ کن حیثیت رکھنے والا",
    englishExample: "She played a pivotal role in the success of the negotiations.",
    urduExample: "اس نے مذاکرات کی کامیابی میں ایک کلیدی اور مرکزی کردار ادا کیا۔",
    synonyms: ["Central", "Crucial", "Vital"]
  }
];

// Categories list for filtering
const CATEGORIES = [
  { id: "All", label: "تمام کیٹیگریز (All)", icon: "🌐" },
  { id: "Daily Life", label: "روزمرہ معمولات (Daily Life)", icon: "☕" },
  { id: "Emotions", label: "جذبات و احساسات (Emotions)", icon: "❤️" },
  { id: "Personality", label: "شخصیت و اوصاف (Personality)", icon: "🌟" },
  { id: "Education", label: "تعلیم و فہم (Education)", icon: "🎓" },
  { id: "Work & Business", label: "دفتر و کاروبار (Work & Career)", icon: "💼" },
  { id: "Health & Fitness", label: "صحت و تندرستی (Health)", icon: "🍎" },
  { id: "Action Verbs", label: "اہم افعال (Action Verbs)", icon: "⚡" },
  { id: "Descriptive", label: "اوصاف و صفات (Adjectives)", icon: "🎨" },
  { id: "Idioms", label: "محاورات و اصطلاحات (Idioms)", icon: "💡" },
  { id: "Society", label: "معاشرہ و اخلاقیات (Society)", icon: "🤝" },
  { id: "Nature", label: "فطرت و موسم (Nature)", icon: "🌿" }
];

const DIFFICULTY_LEVELS = [
  { id: "All", label: "تمام درجات (All Levels)" },
  { id: "Beginner", label: "بنیادی (Beginner)" },
  { id: "Intermediate", label: "درمیانہ (Intermediate)" },
  { id: "Advanced", label: "اعلیٰ (Advanced)" }
];

// ==========================================
// PHRASES DATABASE (انگریزی جملے اور اظہارات)
// ==========================================
const PHRASES_DATA = [
  // --- GREETINGS ---
  { id:1, phrase:"How are you doing?", urduTranslation:"آپ کیسے ہیں؟ / آپ کا کیا حال ہے؟", category:"Greetings", level:"Beginner", explanation:"A casual and friendly way to ask someone about their wellbeing. More informal than 'How do you do?'", urduExplanation:"یہ کسی سے اس کی خیریت پوچھنے کا ایک دوستانہ اور غیر رسمی انداز ہے۔ یہ 'How do you do?' سے زیادہ عام بول چال میں استعمال ہوتا ہے۔", example:"Hey John! How are you doing these days?", urduExample:"ارے جان! آج کل آپ کا کیا حال ہے؟", whenToUse:"Friends, colleagues, casual meetings" },
  { id:2, phrase:"Long time no see!", urduTranslation:"بہت عرصے بعد ملے!", category:"Greetings", level:"Beginner", explanation:"Said when you meet someone after a long time. It expresses surprise and happiness.", urduExplanation:"جب آپ کسی سے لمبے عرصے بعد ملیں تو یہ جملہ بولا جاتا ہے۔ اس میں خوشی اور حیرت دونوں کا اظہار ہوتا ہے۔", example:"Oh wow, long time no see! Where have you been?", urduExample:"واہ! بہت عرصے بعد نظر آئے! اتنے عرصے سے کہاں تھے؟", whenToUse:"Meeting old friends after a long gap" },
  { id:3, phrase:"Nice to meet you.", urduTranslation:"آپ سے مل کر خوشی ہوئی۔", category:"Greetings", level:"Beginner", explanation:"A polite phrase used when meeting someone for the first time.", urduExplanation:"کسی سے پہلی بار ملتے وقت شائستگی کا اظہار کرنے والا جملہ۔", example:"Hi, I'm Sara. Nice to meet you!", urduExample:"ہیلو، میں سارہ ہوں۔ آپ سے مل کر بہت خوشی ہوئی!", whenToUse:"First-time introductions in any setting" },
  { id:4, phrase:"Take care!", urduTranslation:"اپنا خیال رکھیں!", category:"Greetings", level:"Beginner", explanation:"A warm farewell phrase expressing concern for someone's wellbeing.", urduExplanation:"رخصت ہوتے وقت پیار سے کہا جانے والا جملہ جس میں دعا اور فکر ہوتی ہے۔", example:"Bye Sara! Take care and stay safe!", urduExample:"الوداع سارہ! اپنا خیال رکھنا اور محفوظ رہنا!", whenToUse:"Saying goodbye to friends and family" },

  // --- OPINIONS ---
  { id:5, phrase:"In my opinion...", urduTranslation:"میرے خیال میں... / میری رائے میں...", category:"Opinions", level:"Beginner", explanation:"Used to introduce your personal view. Signals that what follows is your idea, not a fact.", urduExplanation:"اپنی ذاتی رائے بیان کرنے سے پہلے استعمال ہوتا ہے۔ ظاہر کرتا ہے کہ آگے آنے والی بات آپ کی اپنی رائے ہے۔", example:"In my opinion, we should invest more in education.", urduExample:"میرے خیال میں، ہمیں تعلیم میں زیادہ سرمایہ کاری کرنی چاہیے۔", whenToUse:"Discussions, debates, any conversation" },
  { id:6, phrase:"To be honest...", urduTranslation:"سچ کہوں تو... / صاف بات کریں تو...", category:"Opinions", level:"Beginner", explanation:"Used before sharing a truthful, sometimes frank opinion. Signals sincerity.", urduExplanation:"کوئی سچی یا کھری بات کہنے سے پہلے بولا جاتا ہے۔ اس سے ایمانداری کا احساس ہوتا ہے۔", example:"To be honest, I didn't enjoy the movie very much.", urduExample:"سچ کہوں تو، مجھے یہ فلم زیادہ پسند نہیں آئی۔", whenToUse:"When sharing candid or sensitive feedback" },
  { id:7, phrase:"That makes sense.", urduTranslation:"یہ سمجھ میں آتی ہے بات۔ / یہ منطقی ہے۔", category:"Opinions", level:"Beginner", explanation:"Shows you understand and agree with something explained to you.", urduExplanation:"جب کوئی چیز سمجھ آ جائے یا آپ متفق ہوں تو یہ کہتے ہیں۔", example:"Oh, that makes sense! I never thought of it that way.", urduExample:"اوہ، یہ سمجھ میں آتا ہے! میں نے اس طرح کبھی نہیں سوچا تھا۔", whenToUse:"After receiving an explanation" },
  { id:8, phrase:"I see your point.", urduTranslation:"میں آپ کی بات سمجھتا ہوں۔", category:"Opinions", level:"Intermediate", explanation:"Acknowledges you understand someone's argument, even if you may not fully agree.", urduExplanation:"کسی کی دلیل کو سمجھنے کی تصدیق کرنا، ضروری نہیں کہ پوری طرح متفق ہوں۔", example:"I see your point, but I still think we need more time.", urduExample:"میں آپ کی بات سمجھتا ہوں، لیکن میرے خیال میں ہمیں مزید وقت چاہیے۔", whenToUse:"Debates, professional discussions" },
  { id:9, phrase:"Speak your mind.", urduTranslation:"کھل کر اپنی بات کہنا / دل کی بات بتانا", category:"Opinions", level:"Intermediate", explanation:"To say exactly what you are thinking without hesitation or holding back.", urduExplanation:"بغیر ہچکچاہٹ کے بالکل کھل کر وہی بات کہنا جو آپ سوچ رہے ہیں۔", example:"Please speak your mind — we need honest feedback in this meeting.", urduExample:"براہ کرم کھل کر بتائیں — اس ملاقات میں ہمیں ایمانداری سے رائے چاہیے۔", whenToUse:"Encouraging honesty in discussions" },

  // --- AGREEMENT ---
  { id:10, phrase:"I couldn't agree more.", urduTranslation:"میں بالکل متفق ہوں۔ / بالکل ٹھیک کہا۔", category:"Agreement", level:"Intermediate", explanation:"A strong way to express full agreement. Much stronger than simply 'I agree'.", urduExplanation:"کسی کی بات سے مکمل اتفاق ظاہر کرنے کا بہت زوردار انداز۔ صرف 'I agree' سے کہیں زیادہ پرزور۔", example:"You're right, education is the key to progress. I couldn't agree more!", urduExample:"آپ بالکل درست کہہ رہے ہیں۔ میں بالکل متفق ہوں!", whenToUse:"When strongly agreeing with a statement" },
  { id:11, phrase:"I beg to differ.", urduTranslation:"معذرت کے ساتھ، میں اختلاف کرتا ہوں۔", category:"Agreement", level:"Advanced", explanation:"A polite and formal way to express disagreement without being rude.", urduExplanation:"اختلاف ظاہر کرنے کا نہایت شائستہ اور رسمی انداز — بغیر بے ادبی کے۔", example:"I beg to differ — the data actually shows the opposite trend.", urduExample:"معذرت کے ساتھ اختلاف کروں گا — ڈیٹا دراصل اس کے برعکس رجحان ظاہر کرتا ہے۔", whenToUse:"Formal meetings, debates, professional disagreements" },
  { id:12, phrase:"That's not quite right.", urduTranslation:"یہ بالکل صحیح نہیں ہے۔", category:"Agreement", level:"Intermediate", explanation:"A gentle way of correcting someone without sounding too harsh.", urduExplanation:"کسی کی غلطی کو نرم انداز میں درست کرنا، بغیر سخت لگے۔", example:"That's not quite right — the meeting is on Thursday, not Friday.", urduExample:"یہ بالکل صحیح نہیں — ملاقات جمعرات کو ہے، جمعہ کو نہیں۔", whenToUse:"Politely correcting factual errors" },

  // --- CLARIFICATION ---
  { id:13, phrase:"Could you say that again?", urduTranslation:"کیا آپ یہ دوبارہ کہہ سکتے ہیں؟", category:"Clarification", level:"Beginner", explanation:"A polite way to ask someone to repeat what they said.", urduExplanation:"جب آپ کو کوئی بات سمجھ نہ آئے تو شائستگی سے دوبارہ پوچھنے کا طریقہ۔", example:"I'm sorry, could you say that again? It was a bit noisy.", urduExample:"معذرت، کیا آپ یہ دوبارہ کہہ سکتے ہیں؟ تھوڑا شور تھا۔", whenToUse:"When you miss or don't understand something" },
  { id:14, phrase:"What do you mean by that?", urduTranslation:"آپ کا اس سے کیا مطلب ہے؟", category:"Clarification", level:"Beginner", explanation:"Used to ask for clarification when you don't understand someone's meaning.", urduExplanation:"جب کسی کی بات کا مطلب سمجھ نہ آئے تو وضاحت مانگنے کے لیے استعمال ہوتا ہے۔", example:"What do you mean by that? Are you saying we should cancel the plan?", urduExample:"آپ کا اس سے کیا مطلب ہے؟ کیا آپ کہہ رہے ہیں کہ منصوبہ منسوخ کر دیں؟", whenToUse:"When something is unclear or ambiguous" },
  { id:15, phrase:"Can you elaborate on that?", urduTranslation:"کیا آپ اس پر مزید تفصیل بتا سکتے ہیں؟", category:"Clarification", level:"Intermediate", explanation:"A formal request asking someone to explain in more detail.", urduExplanation:"کسی سے اس کی بات کو زیادہ تفصیل سے سمجھانے کی رسمی درخواست۔", example:"Can you elaborate on the cost breakdown?", urduExample:"کیا آپ اخراجات کی تفصیل پر مزید روشنی ڈال سکتے ہیں؟", whenToUse:"Meetings, academic discussions, interviews" },
  { id:16, phrase:"Bear with me.", urduTranslation:"تھوڑا صبر کریں۔ / میرے ساتھ رہیں۔", category:"Clarification", level:"Intermediate", explanation:"Asking someone to be patient while you take time to do or explain something.", urduExplanation:"جب آپ کو کچھ وقت چاہیے ہو تو سامنے والے سے صبر کرنے کی درخواست۔", example:"Bear with me for a moment — I just need to find the right document.", urduExample:"ایک لمحہ صبر کریں — مجھے بس صحیح دستاویز تلاش کرنی ہے۔", whenToUse:"Presentations, calls, when multitasking" },

  // --- WORKPLACE ---
  { id:17, phrase:"Let's get the ball rolling.", urduTranslation:"آئیں کام شروع کریں۔ / آغاز کریں۔", category:"Workplace", level:"Intermediate", explanation:"To start a process or activity. Motivates a group to begin working.", urduExplanation:"کسی عمل یا سرگرمی کا آغاز کرنے کے لیے استعمال ہونے والا محاورہ۔ ٹیم کو کام شروع کرنے کی ترغیب دیتا ہے۔", example:"We have a lot to cover today, so let's get the ball rolling!", urduExample:"آج ہمارے پاس کافی کام ہے، تو آئیں شروع کرتے ہیں!", whenToUse:"Starting meetings, projects, team tasks" },
  { id:18, phrase:"Touch base with someone.", urduTranslation:"کسی سے رابطہ کرنا / بریف ملاقات کرنا", category:"Workplace", level:"Intermediate", explanation:"To briefly contact or meet with someone to share updates or check on progress.", urduExplanation:"کسی سے مختصر رابطہ کرنا تاکہ حالات کا جائزہ لیا جائے یا اپ ڈیٹ شیئر کی جائے۔", example:"Can we touch base tomorrow morning to discuss the project status?", urduExample:"کیا ہم کل صبح پروجیکٹ کی پیش رفت پر بات کرنے کے لیے ملاقات کر سکتے ہیں؟", whenToUse:"Office communication, team check-ins" },
  { id:19, phrase:"Think outside the box.", urduTranslation:"روایتی سوچ سے ہٹ کر سوچنا", category:"Workplace", level:"Intermediate", explanation:"To think creatively and come up with new, unconventional ideas.", urduExplanation:"روایتی حدود سے باہر نکل کر نئے اور اختراعی خیالات سوچنا۔", example:"We need to think outside the box to solve this problem.", urduExample:"اس مسئلے کو حل کرنے کے لیے ہمیں روایتی سوچ سے ہٹ کر سوچنا ہوگا۔", whenToUse:"Creative sessions, problem-solving" },
  { id:20, phrase:"On the same page.", urduTranslation:"ایک ہی رائے پر ہونا / ہم خیال ہونا", category:"Workplace", level:"Intermediate", explanation:"When everyone in a group has the same understanding or agreement.", urduExplanation:"جب کسی گروہ کے تمام افراد کسی بات پر ایک جیسی سمجھ رکھتے ہوں۔", example:"Before we proceed, let's make sure we're all on the same page.", urduExample:"آگے بڑھنے سے پہلے، آئیں یقین کر لیں کہ ہم سب ایک ہی سمجھ پر ہیں۔", whenToUse:"Team meetings, project kickoffs" },
  { id:21, phrase:"Go the extra mile.", urduTranslation:"اضافی محنت کرنا / حد سے بڑھ کر کوشش کرنا", category:"Workplace", level:"Intermediate", explanation:"To put in more effort than what is expected or required.", urduExplanation:"جتنی ضرورت ہو اس سے بڑھ کر محنت اور کوشش کرنا تاکہ بہترین نتائج حاصل ہوں۔", example:"She always goes the extra mile for her students.", urduExample:"وہ ہمیشہ اپنے طلبہ کے لیے حد سے بڑھ کر محنت کرتی ہے۔", whenToUse:"Describing dedication, work ethic" },
  { id:22, phrase:"Cut to the chase.", urduTranslation:"سیدھی بات کریں / اصل بات پر آئیں", category:"Workplace", level:"Intermediate", explanation:"To get to the main point quickly without wasting time on unnecessary details.", urduExplanation:"فضول تفصیلات میں وقت ضائع کیے بغیر جلدی سے اصل بات پر آنا۔", example:"We don't have much time, so let's cut to the chase — what's the budget?", urduExample:"ہمارے پاس زیادہ وقت نہیں، تو سیدھی بات کریں — بجٹ کیا ہے؟", whenToUse:"Short meetings, time-sensitive conversations" },
  { id:23, phrase:"Back to the drawing board.", urduTranslation:"دوبارہ شروع سے سوچنا / نئے سرے سے منصوبہ بنانا", category:"Workplace", level:"Intermediate", explanation:"To start over with a new plan after something has failed.", urduExplanation:"کسی چیز کے ناکام ہونے کے بعد نئے سرے سے منصوبہ بنانا۔", example:"The prototype didn't work — it's back to the drawing board!", urduExample:"پروٹوٹائپ کام نہیں کیا — دوبارہ نئے سرے سے سوچنا پڑے گا!", whenToUse:"After failed plans, project restarts" },
  { id:24, phrase:"Hit the ground running.", urduTranslation:"فوری طور پر پوری تیاری سے شروع کرنا", category:"Workplace", level:"Intermediate", explanation:"To start a new job or project energetically without needing time to prepare.", urduExplanation:"بغیر تیاری کے وقت لیے، فوری اور مکمل جوش کے ساتھ کسی نئے کام کا آغاز کرنا۔", example:"She hit the ground running on her first day at the new company.", urduExample:"اس نے نئی کمپنی میں پہلے ہی دن سے پوری توانائی کے ساتھ کام شروع کر دیا۔", whenToUse:"Describing enthusiastic beginners or new hires" },

  // --- SOCIAL ---
  { id:25, phrase:"Break the ice.", urduTranslation:"ابتدائی ہچکچاہٹ ختم کرنا / بات چیت کا آغاز کرنا", category:"Social", level:"Intermediate", explanation:"To do or say something to relieve tension in a new social situation.", urduExplanation:"نئی سماجی صورتحال میں اجنبیت یا بے چینی ختم کرنے کے لیے کچھ کہنا یا کرنا۔", example:"He told a funny joke to break the ice at the party.", urduExample:"اس نے پارٹی میں ہنسی مذاق سے بات چیت کا آغاز کیا۔", whenToUse:"New social gatherings, networking events" },
  { id:26, phrase:"Once in a blue moon.", urduTranslation:"کبھی کبھار / بہت کم / نادر", category:"Social", level:"Intermediate", explanation:"Something that happens very rarely or almost never.", urduExplanation:"کوئی چیز جو بہت کم یا نادر ہی ہو۔", example:"He only calls me once in a blue moon.", urduExample:"وہ مجھے بہت کم ہی فون کرتا ہے۔", whenToUse:"Describing rare events or habits" },
  { id:27, phrase:"Spill the beans.", urduTranslation:"راز افشا کرنا / بھید کھولنا", category:"Social", level:"Beginner", explanation:"To reveal secret information, often accidentally or before the right time.", urduExplanation:"راز کو ظاہر کر دینا — اکثر غلطی سے یا وقت سے پہلے۔", example:"Come on, spill the beans! What's the surprise?", urduExample:"بتاؤ بھی! کیا راز ہے؟", whenToUse:"Informal conversation, friendly teasing" },
  { id:28, phrase:"Cost an arm and a leg.", urduTranslation:"بہت مہنگا ہونا / ناک کٹوا کر ملنا", category:"Social", level:"Beginner", explanation:"Something that is extremely expensive — much more than it should reasonably cost.", urduExplanation:"کوئی چیز جو انتہائی مہنگی ہو۔", example:"That handbag costs an arm and a leg — I can't afford it!", urduExample:"وہ ہینڈ بیگ بہت مہنگا ہے — میں اسے خریدنے کی سکت نہیں رکھتا!", whenToUse:"Talking about prices, purchases" },
  { id:29, phrase:"Under the weather.", urduTranslation:"طبیعت ٹھیک نہ ہونا / بیمار محسوس کرنا", category:"Social", level:"Beginner", explanation:"Feeling sick or unwell. A gentle, informal way to say you are ill.", urduExplanation:"بیمار یا بری طبیعت محسوس کرنا۔ بیماری ظاہر کرنے کا ایک نرم غیر رسمی انداز۔", example:"I'm feeling a bit under the weather today, so I'll skip the gym.", urduExample:"آج میری طبیعت کچھ ٹھیک نہیں، اس لیے جم نہیں جاؤں گا۔", whenToUse:"Explaining illness or absence casually" },
  { id:30, phrase:"Pull someone's leg.", urduTranslation:"کسی کو بیوقوف بنانا / مذاق کرنا", category:"Social", level:"Beginner", explanation:"To joke with someone or tease them in a playful, non-harmful way.", urduExplanation:"کسی سے دوستانہ اور بے ضرر انداز میں مذاق کرنا۔", example:"Relax! I'm just pulling your leg — it was a joke!", urduExample:"پریشان نہ ہو! میں تم سے مذاق کر رہا تھا!", whenToUse:"Friendly teasing, humorous conversations" },

  // --- MOTIVATION ---
  { id:31, phrase:"Hang in there!", urduTranslation:"ہمت رکھو! / ڈٹے رہو!", category:"Motivation", level:"Beginner", explanation:"Encouragement to continue despite difficulties. Telling someone not to give up.", urduExplanation:"مشکلات کے باوجود آگے بڑھنے کی حوصلہ افزائی۔ کسی کو ہمت نہ ہارنے کی تاکید۔", example:"Exams are tough, but hang in there — you're almost done!", urduExample:"امتحانات مشکل ہیں، لیکن ہمت رکھو — بس تھوڑا رہ گیا ہے!", whenToUse:"Encouraging someone going through tough times" },
  { id:32, phrase:"Keep up the good work!", urduTranslation:"اسی طرح اچھا کام جاری رکھو!", category:"Motivation", level:"Beginner", explanation:"Praise and encouragement telling someone to continue doing something well.", urduExplanation:"کسی کی تعریف کرتے ہوئے اسے اچھا کام جاری رکھنے کی ترغیب دینا۔", example:"Your sales numbers are impressive. Keep up the good work!", urduExample:"آپ کے فروخت کے اعداد و شمار متاثر کن ہیں۔ اسی طرح جاری رکھیں!", whenToUse:"Praising performance, motivating employees or students" },
  { id:33, phrase:"Every cloud has a silver lining.", urduTranslation:"ہر مشکل میں کچھ نہ کچھ فائدہ ہوتا ہے۔", category:"Motivation", level:"Intermediate", explanation:"Every difficult situation has a positive aspect if you look for it.", urduExplanation:"ایک ضرب المثل جس کا مطلب ہے کہ ہر مشکل صورتحال میں کوئی نہ کوئی مثبت پہلو ضرور ہوتا ہے۔", example:"Losing that job was hard, but every cloud has a silver lining — I found a much better one!", urduExample:"وہ نوکری جانا مشکل تھا، لیکن ہر برے وقت میں کچھ اچھا بھی ہوتا ہے!", whenToUse:"Consoling someone, finding hope in difficulty" },
  { id:34, phrase:"It's not the end of the world.", urduTranslation:"یہ کوئی قیامت نہیں ہے۔ / اتنی بڑی بات نہیں۔", category:"Motivation", level:"Beginner", explanation:"Comforting someone by saying a bad situation is not as serious as it may seem.", urduExplanation:"کسی کو تسلی دینے کے لیے کہا جاتا ہے کہ یہ صورتحال اتنی بری نہیں جتنی لگ رہی ہے۔", example:"You failed one exam? It's not the end of the world — you can retake it!", urduExample:"ایک امتحان میں فیل ہو گئے؟ کوئی قیامت نہیں آئی — دوبارہ دے سکتے ہو!", whenToUse:"Comforting someone after failure or disappointment" },

  // --- POLITE REQUESTS ---
  { id:35, phrase:"Would you mind if I...?", urduTranslation:"کیا آپ کو اعتراض ہوگا اگر میں...؟", category:"Polite Requests", level:"Intermediate", explanation:"A very polite way to ask for permission before doing something.", urduExplanation:"کوئی کام کرنے سے پہلے بہت شائستہ انداز میں اجازت مانگنا۔", example:"Would you mind if I opened the window? It's getting warm.", urduExample:"کیا آپ کو اعتراض ہوگا اگر میں کھڑکی کھولوں؟ گرمی لگ رہی ہے۔", whenToUse:"Formal situations, asking sensitive permissions" },
  { id:36, phrase:"If you don't mind me asking...", urduTranslation:"اگر آپ کو برا نہ لگے تو...", category:"Polite Requests", level:"Intermediate", explanation:"A polite way to introduce a question that might be personal or intrusive.", urduExplanation:"کوئی ذاتی یا حساس سوال پوچھنے سے پہلے شائستگی کا مظاہرہ کرنا۔", example:"If you don't mind me asking, how did you get that promotion so quickly?", urduExample:"اگر آپ کو برا نہ لگے تو، آپ کو اتنی جلدی ترقی کیسے ملی؟", whenToUse:"Asking personal or sensitive questions politely" },
  { id:37, phrase:"I appreciate your help.", urduTranslation:"میں آپ کی مدد کی قدر کرتا/کرتی ہوں۔", category:"Polite Requests", level:"Beginner", explanation:"A sincere way to express gratitude for someone's assistance.", urduExplanation:"کسی کی مدد کے لیے خلوص دل سے شکریہ اور قدردانی کا اظہار کرنا۔", example:"Thank you so much. I really appreciate your help with this project.", urduExample:"بہت شکریہ۔ میں اس پروجیکٹ میں آپ کی مدد کا واقعی قدردان ہوں۔", whenToUse:"Thanking colleagues, teachers, friends" },

  // --- TIME ---
  { id:38, phrase:"In the nick of time.", urduTranslation:"بالکل عین وقت پر / آخری لمحے میں", category:"Time", level:"Intermediate", explanation:"Just at the last possible moment before it is too late.", urduExplanation:"بالکل آخری وقت پر — جب دیر ہونے والی تھی۔", example:"We arrived at the airport in the nick of time — the gate was about to close!", urduExample:"ہم بالکل عین وقت پر ایئرپورٹ پہنچے — گیٹ بند ہونے ہی والا تھا!", whenToUse:"Describing last-minute arrivals or rescues" },
  { id:39, phrase:"Better late than never.", urduTranslation:"دیر آید درست آید", category:"Time", level:"Beginner", explanation:"It is better to do something late than to not do it at all.", urduExplanation:"یہ ضرب المثل کہتی ہے کہ دیر سے کرنا نہ کرنے سے بہتر ہے۔", example:"He finally apologized after two years — better late than never!", urduExample:"اس نے دو سال بعد معافی مانگی — دیر آید درست آید!", whenToUse:"Commenting on delayed but welcome actions" },
  { id:40, phrase:"Time flies when you're having fun.", urduTranslation:"خوشی میں وقت پَر لگا کر اڑتا ہے۔", category:"Time", level:"Beginner", explanation:"Time seems to pass very quickly when you are enjoying yourself.", urduExplanation:"جب انسان مزے میں ہو تو وقت بہت تیزی سے گزر جاتا ہے۔", example:"We've been talking for three hours! Time flies when you're having fun.", urduExample:"ہم تین گھنٹے سے باتیں کر رہے ہیں! مزے میں وقت کیسے اُڑ جاتا ہے۔", whenToUse:"After an enjoyable event or gathering" },

  // --- ADVANCED ---
  { id:41, phrase:"The elephant in the room.", urduTranslation:"وہ اہم بات جسے سب نظر انداز کر رہے ہوں", category:"Advanced", level:"Advanced", explanation:"An obvious problem people are aware of but deliberately avoid discussing.", urduExplanation:"ایک واضح مسئلہ جس کے بارے میں سب جانتے ہوں لیکن جان بوجھ کر بات کرنے سے گریز کریں۔", example:"No one mentioned the budget cuts — it was truly the elephant in the room.", urduExample:"کسی نے بجٹ کٹوتیوں کا ذکر نہیں کیا — یہ واقعی وہ اہم بات تھی جسے سب نظر انداز کر رہے تھے۔", whenToUse:"Pointing out ignored but important issues" },
  { id:42, phrase:"Bite off more than you can chew.", urduTranslation:"اپنی طاقت سے زیادہ کام لینا", category:"Advanced", level:"Intermediate", explanation:"To take on more responsibility than you can realistically handle.", urduExplanation:"اپنی استطاعت سے زیادہ کام یا ذمہ داری اٹھا لینا۔", example:"He accepted five projects at once and clearly bit off more than he could chew.", urduExample:"اس نے ایک ساتھ پانچ پروجیکٹ قبول کر لیے اور اپنی طاقت سے زیادہ کام لے لیا۔", whenToUse:"Warning someone about overcommitting" },
  { id:43, phrase:"Don't beat around the bush.", urduTranslation:"گول مول بات نہ کرو / سیدھی بات کرو", category:"Advanced", level:"Intermediate", explanation:"Stop avoiding the main point and say what you mean directly.", urduExplanation:"گول مول باتیں چھوڑو اور سیدھا اصل مدعا بتاؤ۔", example:"Stop beating around the bush and tell me what the real issue is!", urduExample:"گول مول بات بند کرو اور مجھے بتاؤ کہ اصل مسئلہ کیا ہے!", whenToUse:"When someone is being evasive or indirect" },
  { id:44, phrase:"A blessing in disguise.", urduTranslation:"زحمت میں رحمت / ظاہری نقصان جو فائدہ بنے", category:"Advanced", level:"Intermediate", explanation:"Something that seems bad at first but turns out to be good in the end.", urduExplanation:"ایسی چیز جو شروع میں بری لگے لیکن آخر میں فائدہ مند ثابت ہو۔", example:"Getting rejected from that job was a blessing in disguise — I found an even better one!", urduExample:"اس نوکری سے رد ہونا زحمت میں رحمت نکلا!", whenToUse:"Looking for positives in negative situations" },
  { id:45, phrase:"Let the cat out of the bag.", urduTranslation:"راز افشا ہو جانا / بھید کھل جانا", category:"Advanced", level:"Intermediate", explanation:"To accidentally reveal a secret or surprise that was supposed to be kept hidden.", urduExplanation:"جانے انجانے میں کوئی راز ظاہر کر دینا جسے چھپانا تھا۔", example:"Oops! I let the cat out of the bag about Sara's surprise party.", urduExample:"افسوس! میں نے سارہ کی سرپرائز پارٹی کا راز کھول دیا۔", whenToUse:"When a secret is revealed accidentally" },
  { id:46, phrase:"Bite the bullet.", urduTranslation:"تکلیف برداشت کرنا / انا کو مارنا", category:"Advanced", level:"Intermediate", explanation:"To endure a painful or difficult situation with courage and patience.", urduExplanation:"کسی تکلیف دہ صورتحال کو بہادری اور صبر سے برداشت کرنا۔", example:"I bit the bullet and apologized, even though it was hard.", urduExample:"میں نے انا مار کر معافی مانگ لی، چاہے یہ مشکل تھا۔", whenToUse:"Doing something difficult but necessary" },
  { id:47, phrase:"On the fence.", urduTranslation:"دو رائوں کے درمیان / فیصلہ نہ کر پانا", category:"Advanced", level:"Intermediate", explanation:"To be undecided or neutral about something. Unable to make a clear choice.", urduExplanation:"کسی معاملے میں غیر فیصلہ کن ہونا — دو اختیارات کے درمیان فیصلہ نہ کر پانا۔", example:"I'm still on the fence about whether to move abroad or stay here.", urduExample:"میں ابھی تک فیصلہ نہیں کر پایا کہ بیرون ملک جاؤں یا یہاں رہوں۔", whenToUse:"Expressing indecision, discussing choices" },
  { id:48, phrase:"Hit the nail on the head.", urduTranslation:"بالکل ٹھیک بات کہنا / نشانے پر لگنا", category:"Advanced", level:"Intermediate", explanation:"To say or do something exactly right. To identify the precise problem.", urduExplanation:"بالکل صحیح بات کہنا یا کسی مسئلے یا حل کی صحیح نشاندہی کرنا۔", example:"You hit the nail on the head — that's exactly the problem!", urduExample:"آپ نے بالکل ٹھیک پکڑا — یہی تو اصل مسئلہ ہے!", whenToUse:"Praising accurate observations or correct answers" }
];

const PHRASE_CATEGORIES = [
  { id: "All",             label: "تمام (All Phrases)",               icon: "🗣️" },
  { id: "Greetings",       label: "سلام و آداب (Greetings)",           icon: "👋" },
  { id: "Opinions",        label: "رائے اور خیالات (Opinions)",         icon: "💬" },
  { id: "Agreement",       label: "اتفاق و اختلاف (Agreement)",         icon: "🤝" },
  { id: "Clarification",   label: "وضاحت (Clarification)",              icon: "❓" },
  { id: "Workplace",       label: "دفتری جملے (Workplace)",             icon: "💼" },
  { id: "Social",          label: "سماجی جملے (Social)",               icon: "🌐" },
  { id: "Motivation",      label: "حوصلہ افزائی (Motivation)",          icon: "🚀" },
  { id: "Polite Requests", label: "شائستہ گزارشات (Polite)",            icon: "🙏" },
  { id: "Time",            label: "وقت کے جملے (Time)",                icon: "⏰" },
  { id: "Advanced",        label: "اعلیٰ درجے کے جملے (Advanced)",      icon: "⭐" }
];
